<?php if(!$this->private || ($this->private && isset($_SESSION['external_user']))):?>
<?php if($this->products): 
//translate library
$lang = Zend_Registry::get ( 'Zend_Translate' );

$value = $this->products; ?>
<div class="row-fluid">		

	<div class="col-md-12 no-margin overflow_hidden jump">
		<div class="row-fluid">
			<div class="fixed_internal_content">		
				
				<?php 
				$product = '<div><div class="col-md-2 pointer">';
				$product .= '<img id="catalog_prod_'.$value["id"].'" product_id="'.$value["id"].'" class="preview_list_img thumbnail"';
				$product.= ' style="border: thin solid; color: black !important;"';
				$product .= ' src="/uploads/products/' . $value['image'] .'" width="100px"/>';
				$product .= '</div>
							<div class="col-md-5">
								<div id="catalog_prod_name_'.$value["id"].'" class="pointer row-fluid" product_id="'.$value["id"].'"><b>'.$value['name'].'</b></div>
				                <div class="row-fluid" style="text-align:justify;"><p>'.substr($value['description'], 0, 200)."...".'</p></div>
							</div>			
							</div>';

				$product .= '<div class="hide"><div class="col-md-8" id="catalog_container"></div></div>';
				
			
				?>		
				<?php echo $product; ?>
			</div>
		</div>
	</div>

</div>
<?php endif; ?>
<?php elseif (!$this->login): ?>
<div class="row-fluid">
	<?php 	echo $this->previewHelper(null,null,$this->area); ?>
</div>
<?php endif; ?>
