<!-- 
 *	View that contains a form to search for contents
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   Diego Perez
 -->


<?php $lang = Zend_Registry::get('Zend_Translate');?>
<div class="row-fluid">
	<div class="span12 center page-header-wica">
		<h1><?php echo $lang->translate('Link Banners');?></h1>
	</div>
</div>

<div class="row-fluid">
	<div class="span12 page-header center">
		<h3><?php echo $lang->translate('Search criteria');?></h3>
	</div>
</div>

<div class="row-fluid">
	<div class="span12 center">
		<form id="<?php echo $this->form->getId() ?>" action="" method="<?php echo $this->form->getMethod() ?>" class="well" enctype="<?php echo $this->form->getAttrib('enctype'); ?>" >
			<div class="row-fluid">
                <div class="span6 form_label">
		             <label class="required" for="text"><?php echo $this->form->text->getLabel(); ?></label>
	            </div>
	            <div class="span2 form_field">
	                 <?php echo $this->form->text->renderViewHelper(); ?>
	            </div>
            </div>
            <div class="row-fluid">
                <div class="span6 form_label">
		             <label class="required" for="section"><?php echo $this->form->section->getLabel(); ?></label>
	            </div>
	            <div class="span2 form_field">
	                 <?php echo $this->form->section->renderViewHelper(); ?>
	            </div>
            </div>
            <input type="hidden" id="section_tree_id" name="section_tree_id" value="<?php echo $this->section_tree_id?>">
            <div class="row-fluid center">
	              <?php echo $this->form->submit_link_search_form->renderViewHelper(); ?>
	              <!-- <input type="button" class="btn btn-primary" id ="submit_link_search_form" value="<?php //echo $lang->translate('Search'); ?>"/>  -->
            </div>
		</form>
	</div>
</div>


<?php if(count($this->content_results)>0):?>

<div class="row-fluid">
	<div class="span12 page-header center">
		<h3><?php echo $lang->translate('Search results');?></h3>
	</div>
</div>

<div class="line-top alert_messages_container" id="alerts">
	<div class="alert alert-error hide size_alerts" id="alerts-inner">
	</div>
</div>
	
<form action="" name="" id="frmLinkObjects" method="post">
	<div class="row-fluid link-container">
		<div class="span12 form-inline center">
			<label><b><?php echo '*'.$lang->translate('Link to section').':'; ?></b></label> <input type="text" name="related_section" id="related_section" value="<?php echo isset($this->section)? $this->section->title : ''; ?>"/> 
			<input type="hidden" name="section_id" id="section_id" title="<?php echo $lang->translate('Required section'); ?>" value="<?php echo isset($this->section->section_id)? $this->section->section_id : $this->section->id; ?>"/>
		</div>
	</div>	
	<div class="row-fluid">
		<div class="span12 page-header-wica center">
			<h3><?php echo $lang->translate('Banners list'); ?></h3>
		</div>
	</div>
	<div class="results_table_container">
		<input type="hidden" name="content_sel" id="content_sel" title="<?php echo $lang->translate('Required content'); ?>"/>
		<table class="table table-bordered">
			<tr>
				<th><?php echo $lang->translate('Name'); ?></th>
				<th><?php echo $lang->translate('Description');?></th>
				<th><?php echo $lang->translate('Banner type'); ?></th>
				<th><?php echo $lang->translate('Status');?></th>
				<th><?php echo $lang->translate('Location');?></th>
				<th><?php echo $lang->translate('Actions'); ?></th>
			</tr>
			<?php foreach ($this->content_results as $key => $content): ?>
  			<tr class="<?php if(($key+1)%2): echo "odd"; endif;?>">
				<td><?php echo utf8_encode($content['name']); ?></td>
				<td><?php echo utf8_encode($content['description']);?></td>
				<td><?php echo $lang->translate(utf8_encode($content['banner_type']));?></td>
				<td><?php echo $lang->translate(utf8_encode($content['status']));?></td>
				<td><?php echo $lang->translate('Section').': '.utf8_encode($content['section_name']); ?> </td>
				<td style="text-align: center"><input type="checkbox" name="objects[<?php echo $content['id']; ?>][status]" id="object_<?php echo $content['id']; ?>"> </td>
			</tr>
  			<?php endforeach ?>
  		</table>
	</div>

	<div class="row-fluid link-container">
		<div class="span12 form-inline center">			 
			<input type="button" class="btn btn-primary" id ="btnLink" value="<?php echo $lang->translate('Connect'); ?>"/>
		</div>
	</div>
</form>

<?php else:?>
<div class="row-fluid center">
	<?php if($this->showresults):?>
		<h3><?php echo $lang->translate('No Banners Found');?></h3>
	<?php endif;?>
</div>
<?php endif;?>
