<?php 
/**
 * New View. Renders the view of the New action 
 *
 * @category   WicaWeb
 * @package    Core_View_Template_New
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Santiago Arellano
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>
<div class="row-fluid line">
	<div class="span12 page-header-wica center line">
		<h1><?php echo $lang->translate('Edit Template');?></h1>
	</div>
</div>

<div class="line-top alert_messages_container">
        <?php echo $this->flashMessages();?>
</div>

<div class="row-fluid">
    <div class="span12">
      <form id="<?php echo $this->form->getId() ?>" action="" method="<?php echo $this->form->getMethod() ?>" class="well" enctype="<?php echo $this->form->getAttrib('enctype'); ?>" >  
          <div class="row-fluid">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required"><?php echo $this->form->name->getLabel(); ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span4 form_field">
                            <?php echo $this->form->name->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required"><?php echo $this->form->template_file->label_name; ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span5 form_field">
                            <input class="align-top" readonly type="text" id="input_template_file" name="input_template_file"/>
							<?php echo $this->form->template_file->renderViewHelper(); ?>&ensp;<a href="<?php echo '/core/template_template/download?file='.$this->form->hdn_template_file->getValue().'&url='.str_replace('/', '@@@', APPLICATION_PATH . '/../application/modules/default/views/scripts/partials/'.$this->form->hdn_template_file->getValue()); ?>" title="<?php echo $lang->translate('Download'); ?>"><i class="icon-download-alt"></i></a>
							<a href="/core/template_template/view?id=<?php echo $this->template_id;?>" title="<?php echo $lang->translate('View code'); ?>"><i class="icon-indent-left"></i></a>		
							<?php echo $this->form->hdn_template_file->renderViewHelper(); ?>
							<span id='error_no_area' class="hide">
								<label class="error_validation" ><?php echo $lang->translate('Not found any valid area');?></label>
							</span>	
							<span id='error_empty_file' class="hide">
								<label class="error_validation" ><?php echo $lang->translate('Empty file');?></label>
							</span>	
							<span id='error_file' class="hide">
								<label class="error_validation" ><?php echo $lang->translate('File error');?></label>
							</span>		
							<span id='error_invalid_structure' class="hide">
								<label class="error_validation" ><?php echo $lang->translate('Invalid structure');?></label>
							</span>	
							<p class="help-block grey">(phtml)</p>
                        </div>
                    </div>
                </div>
          </div>
          <div class="row-fluid">                        
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required"><?php echo  $this->form->template_image->label_name; ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span5 form_field">
                            <input class="align-top" readonly type="text" id="input_template_image" name="input_template_image"/>
							<?php echo $this->form->template_image->renderViewHelper(); ?>&ensp;<a href="<?php echo '/core/template_template/download?file='.$this->form->hdn_template_image->getValue().'&url='.str_replace('/', '@@@', APPLICATION_PATH . '/../public/uploads/template_img/'.$this->form->hdn_template_image->getValue()); ?>" title="<?php echo $lang->translate('Download'); ?>"><i class="icon-download-alt" ></i></a>
							<?php echo $this->form->hdn_template_image->renderViewHelper(); ?>
							<p class="help-block grey">(jpg,jpeg,png,gif)</p>
                        </div>
                    </div>
                </div>  
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required"><?php echo  $this->form->css_files->label_name; ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span5 form_field">
							<?php echo $this->form->css_files->renderViewHelper(); ?>
							<ul id="css_files_list" class="line-top">
							<?php $aux_css_files = (explode(',',$this->css_files)); 
								array_pop($aux_css_files);
								$aux_media_css = (explode(',',$this->media_css));
								array_pop($aux_media_css);
								if($aux_css_files)
								foreach($aux_css_files as $key_css => $aii){ ?>
									<li id='css_file_<?php echo str_replace('.', '', $aii)?>' >
										<?php echo substr($aii, 0,30);?>... &ensp;<a href="<?php echo '/core/template_template/download?file='.$aii.'&url='.str_replace('/', '@@@', APPLICATION_PATH . '/../public/css/templates/'.$this->template_name.'/'.$aii); ?>" title="<?php echo $lang->translate('Download'); ?>"><i class="icon-download-alt" ></i></a><br/>
										&ensp;media:&ensp;<input type='text' id='media_css_<?php echo str_replace('.', '', $aii)?>' name='media_css_<?php echo str_replace('.', '', $aii)?>' value="<?php if($aux_media_css){ if($aux_media_css[$key_css]!='null'){echo $aux_media_css[$key_css];} } ?>"/>
										&ensp;<a id='delete_css_<?php echo str_replace('.', '', $aii)?>' title='Borrar' index='<?php echo $aii;?>' li='css_file_<?php echo str_replace('.', '', $aii)?>' old="yes" template="<?php echo $this->template_name; ?>" >
											<i class='icon-trash'></i>
										</a>
									</li>
								<?php }?>								
							</ul>
							
                        </div>
                        
                    </div>
                </div>                               
		 </div>
          <div class="row-fluid">                        
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required"><?php echo  $this->form->image_files->label_name; ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span5 form_field">
							<?php echo $this->form->image_files->renderViewHelper(); ?>
							<ul id="image_files_list" class="line-top">
							
							<?php $aux_image_files = (explode(',',$this->images_files)); 
								array_pop($aux_image_files);
								foreach($aux_image_files as $aii){ ?>
									<li id='image_file_<?php echo str_replace('.', '', $aii)?>' >
										<?php echo substr($aii, 0,30);?>...&ensp;<a href="<?php echo '/core/template_template/download?file='.$aii.'&url='.str_replace('/', '@@@', APPLICATION_PATH . '/../public/images/templates/'.$this->template_name.'/'.$aii); ?>" title="<?php echo $lang->translate('Download'); ?>"><i class="icon-download-alt"></i></a>
										&ensp;<a id='delete_image_<?php echo str_replace('.', '', $aii)?>' title='Borrar' index='<?php echo $aii;?>' li='image_file_<?php echo str_replace('.', '', $aii)?>'  old="yes" template="<?php echo $this->template_name; ?>"  >
											<i class='icon-trash'></i>
										</a>
									</li>
								<?php }?>							
							
							</ul>

                        </div>
                        
                    </div>
                </div>     
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required"><?php echo  $this->form->js_files->label_name; ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span5 form_field">
							<?php echo $this->form->js_files->renderViewHelper(); ?>   
							<ul id="js_files_list" class="line-top">
							<?php $aux_js_files = (explode(',',$this->js_files)); 
								array_pop($aux_js_files);
								foreach($aux_js_files as $aii){ ?>
									<li id='js_file_<?php echo str_replace('.', '', $aii)?>' >
										<?php echo substr($aii, 0,30);?>...&ensp;<a href="<?php echo '/core/template_template/download?file='.$aii.'&url='.str_replace('/', '@@@', APPLICATION_PATH . '/../public/js/templates/'.$this->template_name.'/'.$aii); ?>" title="<?php echo $lang->translate('Download'); ?>"><i class="icon-download-alt" ></i></a>
										&ensp;<a id='delete_js_<?php echo str_replace('.', '', $aii)?>' title='Borrar' index='<?php echo $aii;?>' li='js_file_<?php echo str_replace('.', '', $aii)?>' old="yes" template="<?php echo $this->template_name; ?>"  >
											<i class='icon-trash'></i>
										</a>
									</li>
								<?php }?>								
							</ul>                     
                        </div>
                        
                    </div>
                </div>                            
		 </div>		 
          <div class="row-fluid">
				<div class="center">
					<div class="row-fluid">
						<?php echo $this->form->submit_btn->renderViewHelper(); ?>
					</div>
				</div>
			</div>
			
		<div id="div_read_file" class="hide"></div>	
		<input type="hidden" id="hdn_areas" name="hdn_areas" value="" />
		<input type="hidden" id="repeat_template" value="<?php echo $lang->translate('The template name already exist');?>" />
		<input type="hidden" id="template_id" name="template_id" value="<?php echo $this->template_id; ?>" />
		<input type="hidden" id="template_name" name="template_name" value="<?php echo $this->template_name?>" />
		<input type="hidden" id="hdn_css_files" name="hdn_css_files" value="" />
		<input type="hidden" id="hdn_media_css" name="hdn_media_css" value="" />
		<input type="hidden" id="hdn_js_files" name="hdn_js_files" value="" />
		<input type="hidden" id="hdn_image_files" name="hdn_image_files" value="" />		
		<input type="hidden" id="file_already_exist" name="file_already_exist" value="<?php echo $lang->translate('File already exist')?>" />
		<input type="hidden" id="file_too_big" name="file_too_big" value="<?php echo $lang->translate('The file size is too big')?>" />
		<input type="hidden" id="invalid_extension" name="invalid_extension" value="<?php echo $lang->translate('Invalid extension')?>" />
		<input type="hidden" id="template_folder" name="template_folder" value="<?php echo 'template_'.time(); ?>" />
      </form>
    </div>
</div> 