<?php 
/**
 * Index View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_Website_Index
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Santiago Arellano
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<?php foreach($this->template_links as $action_id => $opt): ?>
<?php if($opt['action']=='new'): ?>
<div class="row-fluid option_bar_container">
	<ul class="nav nav-pills pull-right">
        <li>
            <a href="/core/template_template/new"><?php echo $lang->translate('Add New Template'); ?></a>
        </li>
    </ul>
</div>
<?php endif; ?>
<?php endforeach; ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="row-fluid">
	<div class=" page-header-wica span12 center line">
		<h1> <?php echo $lang->translate('Upload Template');?> </h1>
	</div>
</div>

<div class="row-fluid">
<?php if($this->templates && count($this->templates)>0):?>
		
	<?php if($this->templates && count($this->templates)>0):?>
		<div class="row-fluid center line">
			<h3> <?php echo $lang->translate('Available Templates');?> </h3>
		</div>
	
		 <div class="row-fluid">
		     <table class="table table-bordered table-bordered-wica">
				<tr>
					<th> <?php echo $lang->translate('Image');?> </th>
					<th> <?php echo $lang->translate('Name');?> </th>
					<th> <?php echo $lang->translate('Tools');?> </th>
				</tr>
				<?php foreach ($this->templates as $t => $template): ?> 
				<tr class="<?php if(($t+1)%2): echo "odd"; endif;?>">
					<td  class="center"><img id="img_render_<?php echo $template->id;?>" template_id="<?php echo $template->id;?>" src="<?php echo '/uploads/template_img/'.$template->image; ?>" width="100px" /></td>
					<td><?php echo $template->name?></td>
					<td>
						
						<?php foreach($this->template_links as $action_id => $opt): ?>
							<?php if($opt['action']=='edit'): ?>
								<a href="/core/template_template/edit?id=<?php echo $template->id;?>" title="<?php echo $lang->translate('Update'); ?>"><i class="icon-pencil"></i></a>
								/
							<?php endif; ?>
							<?php if( ! in_array($template->id, $this->active_templates) ){ ?>
								<?php if($opt['action']=='delete'): ?>
									<a href="/core/template_template/delete?id=<?php echo $template->id;?>" title="<?php echo $lang->translate('Delete'); ?>"><i class="icon-trash"></i></a>
									/
								<?php endif; ?>		
							<?php }?>				
						<?php endforeach; ?>
						
						<a href="/core/template_template/view?id=<?php echo $template->id;?>" title="<?php echo $lang->translate('View code'); ?>"><i class="icon-indent-left"></i></a>			
					</td>
				</tr>	
				<?php endforeach;?>
			</table>
		 </div>	
		 
	<a id="anchor_render" class="hide" href="#render_template"></a>
	<div style="display: none">
		<div class="span12" id="render_template">
			
		</div>

	</div>
	
	<?php endif;?>
		
<?php else:?>
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No Templates Available Yet');?></h3>
	</div>
<?php endif;?>
</div>