<?php 
/**
 * New View. Renders the view of the New action 
 *
 * @category   WicaWeb
 * @package    Core_View_Template_View
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Santiago Arellano
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>
<div class="row-fluid line">
	<div class="span12 page-header-wica center line">
		<h1><?php echo $lang->translate('View Template File');?></h1>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
        <?php echo $this->flashMessages();?>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
    	<div class="row-fluid">
	    	<div class="span3">&nbsp;</div>
	    	<div class="span6 well">
	    		<h2 class="center"><?php echo $lang->translate('Template file').': '. $this->file_name;?></h2>
		       <?php 
			       foreach($this->template_file as $f):
			       		echo htmlentities( $f ).'<br/>';
			       endforeach;
		       ?>
	       </div>
	       <div class="span3">&nbsp;</div>
	      </div>
    </div>
</div> 