<?php 
/**
 * New View. Renders the view of the New action 
 *
 * @category   WicaWeb
 * @package    Core_View_Template_View
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Santiago Arellano
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript" src="/js/modules/core/template/edit_file.js"></script>
<div class="container-fluid center">
    <div class="page-header-wica center">
		<h1><?php echo $lang->translate('View Template File');?></h1>
	</div>
</div>

<div class="container-fluid">
	<div class="col-md-12">
        <?php echo $this->flashMessages();?>
    </div>
</div>


<div class="container-fluid">
    <div class="row">
            
            <div class="col-md-8 col-md-offset-2 well">
                <h2 class="center"><?php echo $lang->translate('Template file').': '. $this->file_name;?></h2>
                <form method="POST" action="/core/template_template/editfile?id=<?php echo $this->id ?>">
                    <textarea id="code" name="code">
                        <?php 
                                foreach($this->template_file as $f):
echo htmlentities( $f );
                                endforeach;
                        ?>
                    </textarea>
                    <div class="center" style="margin-top: 15px;">
                        <input id="save" class="btn btn-primary" type="submit" value="Save" name="save">
                        <input id="cancel" class="btn btn-primary" type="button" value="Cancel" name="cancel">
                    </div>
                </form>
           </div>
           
          </div>
</div>

<script type="text/javascript">
        var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
            lineNumbers: true,
            styleActiveLine: true,
            matchBrackets: true,
            lineWrapping: true,
            mode: "javascript"
        });
</script>