<?php 
/**
 * ControlPanel View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_Index_ControlPanel
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<div class="row-fluid line">
	<div class="span12 page-header-wica center">
		<h1> <?php echo $lang->translate('Control Panel');?> </h1>
	</div>
</div>
<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="well">
	<div class="row-fluid">
		<ul id="control_panel_options" class="nav nav-pills">
			<?php foreach($this->menu_modules as $module):?>
				<li class="control_panel_opt"><a href='/<?php echo $module['action']?>' class="center"><?php if($module['image']):?><img alt="<?php echo $lang->translate($module['name']);?>" src="/images/controlPanel/<?php echo $module['image'];?>" class="control_panel_image"><?php endif;?><?php echo $lang->translate($module['name']);?></a></li>
			<?php endforeach;?>
		</ul>
	</div>	
	
	<div class="row-fluid">
		<form id="<?php echo $this->select->getId() ?>" action="<?php echo $this->select->getAction(); ?>" method="<?php echo $this->select->getMethod() ?>" enctype="<?php echo $this->select->getAttrib('enctype'); ?>" >
			<div class="form-inline website_picker">
				<label class="required" for="section"><b><?php echo $this->select->websites->getLabel(); ?></b> </label>
				<?php echo $this->select->websites->renderViewHelper(); ?>
			</div>
		</form>
	</div>
</div>