
<div class="row-fluid center_wica_form">
	<div class="span12">
		<form id="<?php echo $this->form->getId() ?>" action=<?php echo $this->form->getAction() ?> method=<?php echo $this->form->getMethod() ?> class=<?php echo $this->form->getAttrib('class') ?> >
				<?php if($this->form->getDescription()!=''):?>
					<div class="row-fluid center">
						<div class="span3">&nbsp;</div>
						<div class="span6 alert alert-error">
							<a class="close" data-dismiss="alert" href="#">×</a>
							<p class=""><?php echo $this->form->getDescription(); ?></p>
						</div>
						<div class="span3">&nbsp;</div>
					</div>
				<?php endif;?>
				<div class="row-fluid">
					<div class="span6 form_label">
						<label class="required" for="username"><?php echo $this->form->username->getLabel(); ?></label>
					</div>
					<div class="span6 form_field">
						<?php echo $this->form->username->renderViewHelper(); ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6 form_label">
						<label class="required" for="password"><?php echo $this->form->password->getLabel(); ?></label>
					</div>
					<div class="span6 form_field">
						<?php echo $this->form->password->renderViewHelper(); ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span12 center">
						<?php echo $this->form->login->renderViewHelper(); ?>
					</div>
				</div>
		</form>
	</div>
</div>