

		<form id="<?php echo $this->form->getId() ?>" action=<?php echo $this->form->getAction() ?> method=<?php echo $this->form->getMethod() ?> class="<?php echo $this->form->getAttrib('class'); ?>" >
				<?php if($this->form->getDescription()!=''):?>
					<div class="form-group text-center">
						<div class="">&nbsp;</div>
						<div class="col-md-6 col-md-offset-3 alert alert-danger">
							<a class="close" data-dismiss="alert" href="#">×</a>
							<p class=""><?php echo $this->form->getDescription(); ?></p>
						</div>
						<div class="col-md-3">&nbsp;</div>
					</div>
				<?php endif;?>
				<div class="form-group">
				    
                                        <label class="required col-md-6 control-label" for="username"><?php echo $this->form->username->getLabel(); ?></label>
					
					<div class="col-md-3">
						<?php echo $this->form->username->renderViewHelper(); ?>
					</div>
				</div>
				<div class="form-group">
				    
                                        <label class="required col-md-6 control-label" for="password"><?php echo $this->form->password->getLabel(); ?></label>
					<div class="col-md-3">
						<?php echo $this->form->password->renderViewHelper(); ?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 center">
						<?php echo $this->form->login->renderViewHelper(); ?>
					</div>
				</div>
		</form>