<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php if (Zend_Auth::getInstance ()->hasIdentity ()) :?>
<?php 
	$id = New Zend_Session_Namespace('id');
	$user_name_info =$id->user_name_info;
	$website_name_info = $id->website_name_info;
?>
<div class="col-md-4">
    <img src="/images/controlPanel/logo-wicaweb.png" alt="WicaWeb 2.0 beta" style="height: 80px;"/>
</div>
<div class="col-md-4 text-center center">
	&nbsp;
</div>
<div class="col-md-4 pull-right text-right">
	
                    <a href='/core/user_user/changepass?id=<?php echo $id->user_id; ?>' >
	      	        <?php echo ($this->escape($lang->translate
                            ('Change Password'),'UTF-8')); ?>
	      	        <i class="glyphicon glyphicon-user"></i> 
		    </a>
    &nbsp;
		
	        
		
        
         <!--Only admin user can generate backups
         test to PuntoNet-->
        <?php if ($id->user_profile == 1) { ?>
        
            <a href='/core/website_website/backup' >
                <?php echo ($this->escape($lang->translate
                    ('Generate Backup'),'UTF-8')); ?>
                <i class="glyphicon glyphicon-download-alt"></i> 
            </a>			
              &nbsp;             
        <?php } ?>
        
                    <a href="/core/index/logout">
	      		<?php echo ($this->escape($lang->translate
                                ('Log Out'),'UTF-8')); ?>
	      		<i class="glyphicon glyphicon-off"></i> 
		    </a> &nbsp;
                    <p>
	<?php echo $this->escape($lang->translate('Website')).':'; ?> 
                <?php if(isset($website_name_info)): echo $website_name_info; else: echo""; endif; ?>
                        <br>
		    <b>
                        <?php echo $this->escape($lang->translate('User')).': '; ?>
                        <?php if(isset($user_name_info)): echo $user_name_info; else: echo""; endif; ?>
                    </b>
                    </p>
</div>
<?php endif;?>
