<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php if (Zend_Auth::getInstance ()->hasIdentity ()) :?>
	<?php if($this->display) : ?>
		<?php $form = New Core_Form_FormSearchBar('searchForm');?>
		<div class="pull-right form-search-bar">
			<form class="<?php echo $form->getAttrib('class'); ?>" id="<?php echo $form->getAttrib('id'); ?>" method="<?php echo $form->getMethod(); ?>" enctype="application/x-www-form-urlencoded">
				<div>
					<ul id="alerts" class="center alerts_section_bar"></ul>
				</div>
				<div class="form-group">
                                    <?php echo $form->select_search_form->renderViewHelper(); ?>

                                    <?php echo $form->nameField->renderViewHelper(); ?>

                                    <?php echo $form->submit_search_form->renderViewHelper(); ?>	
                                </div>
    		</form>
		</div>
	<?php endif;?>
<?php endif;?>
