<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php if (Zend_Auth::getInstance ()->hasIdentity ()) :?>
	<?php if($this->display) : ?>
		<ul class="nav nav-pills pull-right">
			<?php foreach($this->cms_profile_opt as $action_id => $opt): ?>
			<?php if($opt['action']=='new'): ?>
			<li class="pointer" id="section_option">
		    	<a id="new_section">	
		      		<?php echo $this->escape($lang->translate('New Section')); ?> 
				</a>
		    </li>
		    <li class="hide pointer" id="article_option">
		    	<a id="new_article">
		      		<?php echo $this->escape($lang->translate('New article')); ?> 
				</a>     
		    </li>
		    <li class="hide pointer" id="content_option">
		    	<a id="new_content">
		      		<?php echo $this->escape($lang->translate('New Content')); ?> 
				</a>     
		    </li>
		    <?php endif; ?>
		    <?php if($opt['action']=='linksection'): ?>
		    <li class="hide pointer" id="content_link_option">
		        <a id="content_link">
		      		<?php echo $this->escape($lang->translate('Link Content')); ?> 
				</a>
			</li>
			<?php endif; ?>
			<?php endforeach; ?>
		</ul>		
	<?php endif;?>
<?php endif;?>
