<?php $lang = Zend_Registry::get('Zend_Translate'); ?>
<div class="container-fluid">
    <div class="col-md-2 first_row_header">
                    <img src="/images/controlPanel/logo-wicaweb.png" alt="WicaWeb 2.0 beta" style="height: 80px;"/>
    </div>
    <div class="col-md-9 center line-top">
                    <h2><?php echo $lang->translate('WicaWeb Installer Wizard')?></h2>
    </div>
</div>
