 <?php $lang = Zend_Registry::get('Zend_Translate');?>

<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <title><?php echo $this->header['name'];?><?php if($this->title_browser != ''): echo ' - '.$this->title_browser; endif;?></title>
              <?php if($this->id_browser == 1){?>
              <meta property="og:url" content="<?php echo $this->header['website_url'];?>" />
              <?php }else{?>
              <meta property="og:url" content="<?php echo $this->header['website_url'];?><?php echo $this->site_url; ?>" />
              <?php }?>
              <?php if($this->image_browser != ''){?>
                <meta property="og:image" content="<?php echo $this->header['website_url'];?><?php echo $this->image_browser;?>" />    
              <?php }else{ ?>
                <meta property="og:image" content="<?php echo $this->header['website_url'].'/uploads/website/'.$this->header['logo'];?>" />  
              <?php }?>

              <meta property="og:type" content="website" />
              <?php if($this->synopsis_browser != ''){?>
              <meta property="og:description" content="<?php echo $this->synopsis_browser;?>" />
              <?php }else{?>
              <?php if($this->header['meta_descr'] != ''): ?>
              <meta property="og:description" content="<?php echo $this->header['meta_descr'];?>" />
              <?php endif;?>
              <?php }?>
              <?php if($this->title_browser != ''){?>
              <meta property="og:title" content="<?php echo $this->title_browser; ?>" />	
              <?php }else{?>
              <meta property="og:title" content="<?php echo $this->header['name'];?>" />	 
              <?php }?>

              <?php if($this->synopsis_browser != ''){?>
                      <meta name="description" content="<?php echo $this->synopsis_browser;?>" />	
              <?php }else{?>
                  <?php if($this->header['meta_descr'] != ''): ?>
                      <meta name="description" content="<?php echo $this->header['meta_descr'];?>" />	
              <?php endif;?>
              <?php }?>
              <?php if($this->header['meta_keywords'] != ''): ?>
                      <meta name="keywords" content="<?php echo $this->header['meta_keywords'];?>" />	
              <?php endif;?>
              <?php if($this->author_browser != ''){?>
                      <meta name="author" content="<?php echo $this->author_browser;?>" />
              <?php }else{?>
              <?php if($this->header['meta_author'] != ''): ?>
                      <meta name="author" content="<?php echo $this->header['meta_author'];?>" />	
              <?php endif;?>
              <?php }?>
                <?php if($this->header['icon']):?> 
                <link href="/uploads/website/<?php echo $this->header['icon'];?>" type="image/ico" rel="shortcut icon">
                <?php endif;?> 
		<link type="text/css" href="/css/redmond/jquery-ui-1.8.18.custom.css" rel="Stylesheet" />
		<link type="text/css" href="/css/modules/default/bootstrap.css?v3.2.0" rel="Stylesheet" />
		<link type="text/css" href="/css/modules/default/bootstrap-theme.css?v3.2.0" rel="Stylesheet" />	
		<link type="text/css" href="/css/modules/default/front_styles.css" rel="Stylesheet" />		
		<link type="text/css" href="/css/modules/default/sm-core-css.css" rel="Stylesheet" />
                <link type="text/css" href="/css/modules/default/sm-simple.css" rel="Stylesheet" />
				
		<script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>
                <script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
                <script type="text/javascript" src="/js/jquery.cycle2.min.js"></script>
		<script type="text/javascript" src="/js/jquery-ui-1.8.18.custom.min.js"></script>
		<script type="text/javascript" src="/js/bootstrap.min.js?v3.2.0"></script>
		<script type="text/javascript" src="/js/jquery-validation.js"></script>
                <script type="text/javascript" src="/js/ajaxupload.js"></script>
                <script type="text/javascript" src="/js/jquery.smartmenus.min.js"></script>
		
		<!--FANCY BOX -->
		<script type="text/javascript" src="/js/fancybox/jquery.mousewheel-3.0.6.pack.js"></script>
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox.js"></script>
		<link type="text/css" href="/js/fancybox/jquery.fancybox.css" rel="Stylesheet" />
                <!-- Add Button helper (this is optional) -->
                <link rel="stylesheet" type="text/css" href="/js/fancybox/helpers/jquery.fancybox-buttons.css" />
                <script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-buttons.js"></script>
                <!-- Add Thumbnail helper (this is optional) -->
                <link rel="stylesheet" type="text/css" href="/js/fancybox/helpers/jquery.fancybox-thumbs.css" />
                <script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-thumbs.js"></script>
                <!-- Add Media helper (this is optional) -->
                <script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-media.js"></script>		
		<script src='https://www.google.com/recaptcha/api.js'></script>
		<?php include APPLICATION_PATH.'/../public/js/validateMessages.php';?>
  
		<?php echo $this->javascriptHelper() ?>  
		<?php echo $this->externalJavascriptHelper(); ?> 
		<?php echo $this->templateJavascriptFilesHelper(); ?> 
		 
		<?php echo $this->cssHelper() ?>
		<?php echo $this->externalCssHelper(); ?>  
		<?php echo $this->templateCssFilesHelper(); ?> 
		
		<?php include APPLICATION_PATH.'/../public/js/calendar.php';?>
	</head>

	<body>
                <?php if($this->state['type'] == 'online'): ?>					
                        <?php echo $this->layout()->content; ?>										  				
                <?php else: ?>
                        <?php if($this->state['type'] == 'offline'):?>
                                <div class="center">
                                        <h1><?php echo $this->state['display_text']; ?></h1>
                                        <?php if($this->state['display_text']):?>
                                                <img src="/uploads/website/<?php echo $this->state['image']?>" />
                                        <?php endif;?>
                                </div>
                        <?php endif;?>
                        <?php if($this->state['type'] == 'comingsoon'):?>
                                <div class="center">
                                        <h1><?php echo $this->state['display_text']; ?></h1>
                                        <?php if($this->state['display_text']):?>
                                                <img src="/uploads/website/<?php echo $this->state['image']?>" />
                                        <?php endif;?>
                                </div>
                        <?php endif;?>
                        <?php if($this->no_websites=='no'): ?>
                                <?php echo $this->layout()->content; ?>
                        <?php endif; ?>
                <?php endif;?>						  
			
		<!-- Analytics Code -->
		<?php if($this->header['analytics'] != ''):?>
			<script type="text/javascript">
			  	var _gaq = _gaq || [];
				  _gaq.push(['_setAccount', '<?php echo $this->header['analytics'];?>']);
				  _gaq.push(['_trackPageview']);
				
				  (function() {
				    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
				    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
				  })();
			</script>
		<?php endif;?>	  
	</body>
</html>
