<!DOCTYPE HTML>
<html>
	<head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link type="text/css" href="/css/core_design/jquery-ui.css" rel="Stylesheet" />
		<link type="text/css" href="/css/core_design/bootstrap.min.css" rel="Stylesheet" />
		<link type="text/css" href="/css/core_design/bootstrap-theme.min.css" rel="Stylesheet" />
		
                <link type="text/css" href="/css/modules/installer/installer_styles.css" rel="Stylesheet" />
		<link type="text/css" href="/css/modules/core/jquery.autocomplete.css" rel="Stylesheet" />	
		
		<script type="text/javascript" src="/js/jquery-3.3.1.min.js"></script>
                <script type="text/javascript" src="/js/jquery-migrate-1.4.1.min.js"></script>
                <script type="text/javascript" src="/js/jquery.cycle2.min.js"></script>
		<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/js/core_design/bootstrap.min.js"></script>
		<script type="text/javascript" src="/js/jquery-validation.js"></script>
		<script type="text/javascript" src="/js/globalFunctions.js"></script>
		<script type="text/javascript" src="/js/carousel.js"></script>
		<script type="text/javascript" src="/js/ajaxupload.js"></script>
		
		<!--FANCY BOX -->
		<script type="text/javascript" src="/js/fancybox/jquery.mousewheel-3.0.6.pack.js"></script>
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox.js"></script>
		<link type="text/css" href="/js/fancybox/jquery.fancybox.css" rel="Stylesheet" />
                <!-- Add Button helper (this is optional) -->
                <link rel="stylesheet" type="text/css" href="/js/fancybox/helpers/jquery.fancybox-buttons.css" />
                <script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-buttons.js"></script>
                <!-- Add Thumbnail helper (this is optional) -->
                <link rel="stylesheet" type="text/css" href="/js/fancybox/helpers/jquery.fancybox-thumbs.css" />
                <script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-thumbs.js"></script>
                <!-- Add Media helper (this is optional) -->
                <script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-media.js"></script>
		
		<?php echo $this->javascriptHelper(); ?>
		<?php echo $this->cssHelper(); ?>
		<?php include APPLICATION_PATH.'/../public/js/validateMessages.php';?>	 
		
		<script type="text/javascript">
			var document_root = '<?php echo str_replace('\\', '/', APPLICATION_PATH.'/../'); ?>';
		</script>	 
	 	<?php $lang = Zend_Registry::get('Zend_Translate');?>	 
  		<meta http-equiv="content-type" content="text/html; charset=utf-8">
  		<title><?php echo $lang->translate('WicaWeb Installer');?> </title>
</head>
  	<body>
  		<div class="container-fluid">
  			<div class="row header_container line">
  				<?php echo $this->partial("partials/header.phtml"); ?>					
			</div>
			<div class="row line">
			<?php if(!$this->preview_install):?>
				<div class="col-md-2" id="instaler_lengend_container">
					<?php echo $this->partial("partials/legend.phtml"); ?>
				</div>	
				<div class="col-md-10" id="wizard">	
                                    <div id="wizard_container">
                                        <?php echo $this->layout()->content; ?>
                                    </div>
				</div>
			<?php else:?>
				<div class="col-md-12" id="wizard">
					<div id="wizard_container">
						<?php echo $this->layout()->content; ?>
					</div>	
				</div>
			<?php endif;?>
			</div>
		</div>			  
	</body>
</html>