<?php 
/**
 * Edit View. Renders the view of the edit action 
 *
 * @category   WicaWeb
 * @package    Core_View_Website_Edit
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */

//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript" charset="utf-8">
	var username_remote_message = "<?php echo $lang->translate('Username already exist');?>";
    var confirm_password_message = "<?php echo $lang->translate('Passwords does not match');?>";
</script>
<div class="row-fluid">
	<div class="span12 page-header-wica center line">
		<h1><?php echo $lang->translate('Change Password')?></h1>
	</div>
</div>

<div class="line-top alert_messages_container">
     <?php echo $this->flashMessages();?>
</div>

<div class="row-fluid">
    <div class="span12">
      <form id="<?php echo $this->form->getId() ?>" action="" method="<?php echo $this->form->getMethod() ?>" class="well" enctype="<?php echo $this->form->getAttrib('enctype'); ?>" >  
         <div class="row-fluid" id="password_container_old">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required" for="old_password"><?php echo  $this->form->old_password->getDecorator('label')->getOption('requiredPrefix').$this->form->old_password->getLabel(); ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span4 form_field">
                            <?php echo $this->form->old_password->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
           </div>
          <div class="row-fluid" id="password_container_new">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required" for="new_password"><?php echo $this->form->new_password->getDecorator('label')->getOption('requiredPrefix').$this->form->new_password->getLabel(); ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span4 form_field">
                            <?php echo $this->form->new_password->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
              <div class="span6">
                    <div class="row-fluid">
                        <div class="span4 form_label">
                            <label class="required" for="confirm_password"><?php echo $this->form->confirm_password->getDecorator('label')->getOption('requiredPrefix').$this->form->confirm_password->getLabel(); ?></label>
                        </div>
                        <div class="span1">&nbsp;</div>
                        <div class="span4 form_field">
                            <?php echo $this->form->confirm_password->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
          </div>
          <div class="row-fluid">
				<?php echo $this->form->id->renderViewHelper(); ?>
		  </div>  
         </form>
          <div class="row-fluid">
				<div class="center well">
					<div class="row-fluid">
						
						<?php echo $this->form->submit->renderViewHelper(); ?>
						&nbsp;&nbsp;
						<?php echo $this->form->cancel->renderViewHelper(); ?>
					</div>
				</div>
		  </div>
    </div>
</div>