<?php 
/**
 * New View. Renders the view of the New action 
 *
 * @category   WicaWeb
 * @package    Core_View_User_New
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript" charset="utf-8">
	var username_remote_message = "<?php echo $lang->translate('Username already exist');?>";
	var confirm_password_message = "<?php echo $lang->translate('Passwords does not match');?>"; 
</script>

<div class="container-fluid">
	<div class="col-md-12 page-header-wica center line">
		<h1><?php echo $lang->translate('New User');?></h1>
	</div>
</div>
<div class="container-fluid line-top alert_messages_container">
      <?php echo $this->flashMessages();?>
</div>   

<div class="row-fluid">
    <div class="col-md-12">
      <form id="<?php echo $this->form->getId() ?>" action="" method="<?php echo $this->form->getMethod() ?>" class="well form-horizontal" enctype="<?php echo $this->form->getAttrib('enctype'); ?>" >  
          <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="name"><?php echo  $this->form->name->getDecorator('label')->getOption('requiredPrefix').$this->form->name->getLabel(); ?></label>
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->name->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="lastname"><?php echo $this->form->lastname->getDecorator('label')->getOption('requiredPrefix').$this->form->lastname->getLabel(); ?></label>
                        
                        
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->lastname->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
          </div>
          <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="identification"><?php echo $this->form->identification->getLabel(); ?></label>
                        
                       
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->identification->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="email"><?php echo $this->form->email->getLabel(); ?></label>
                     
                        
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->email->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
          </div>
          <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="phone"><?php echo  $this->form->phone->getLabel(); ?></label>
                        
                       
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->phone->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="username"><?php echo $this->form->username->getDecorator('label')->getOption('requiredPrefix').$this->form->username->getLabel(); ?></label>
                        
                        
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->username->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
          </div>
          <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="password"><?php echo  $this->form->password->getDecorator('label')->getOption('requiredPrefix').$this->form->password->getLabel(); ?></label>
                        
                        
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->password->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="confirm_password"><?php echo $this->form->confirm_password->getDecorator('label')->getOption('requiredPrefix').$this->form->confirm_password->getLabel(); ?></label>
                       
                        
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->confirm_password->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
          </div>
          <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        
                        <label class="col-sm-4 control-label form_label required" for="profile"><?php echo  $this->form->profile->getDecorator('label')->getOption('requiredPrefix').$this->form->profile->getLabel(); ?></label>
                   
                        
                        <div class="col-sm-7 col-sm-offset-1">
                            <?php echo $this->form->profile->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    
                </div>
          </div>
          </form>
          <div class="row-fluid">
				<div class="center well">
					<div class="row-fluid">
						
						<?php echo $this->form->submit->renderViewHelper(); ?>
						&nbsp;&nbsp;
						<?php echo $this->form->cancel->renderViewHelper(); ?>
					</div>
				</div>
			</div>
      
    </div>
</div>