
<?php
//translate library
$lang = Zend_Registry::get('Zend_Translate'); 
?>

<script type="text/javascript" charset="utf-8">
	var bannername_remote_message = "<?php echo $lang->translate('Banner name already exist');?>";
</script>

<?php $publication_type = GlobalFunctions::arrayTranslate(Banners_Model_Banners::$publication_type); ?>
     	   
<div class="row-fluid center">
    <div class="page-header-wica center">
        <h1><?php if($this->parent_section):?> <?php echo $lang->translate('Edit banner'); ?> <?php echo $this->parent_section['title']; ?> <?php else: ?> <?php echo $lang->translate('Edit Banner'); ?>   <?php endif;?></h1>		
    </div>
</div>	

<div class="container-fluid line">
	
	<div class="col-md-4 col-md-offset-4 center">
		<div class="btn-group">
			<input type="button" class="btn btn-primary" id="image_btn" value="<?php echo $lang->translate('Image');?>">
			<input type="button" class="btn btn-primary" id="flash_btn" value="<?php echo $lang->translate('Flash');?>">
			<input type="button" class="btn btn-primary" id="html_btn" value="<?php echo $lang->translate('HTML');?>">
		</div>
	</div>
</div>	

<form  id="<?php echo $this->form->getId() ?>" action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>" class="<?php echo $this->form->getAttrib('class'); ?>" enctype="<?php echo $this->form->getAttrib('enctype'); ?>" >
    <div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">
                <label class="col-sm-4 control-label form_label" for="area"><?php echo  $this->form->area->getDecorator('label')->getOption('requiredPrefix').$this->form->area->getLabel(); ?></label>
                <div class="col-sm-8">
                        <?php $this->form->area->setAttrib('container','collapseOptions'); echo $this->form->area->renderViewHelper(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">
                <label class="col-sm-4 control-label form_label" for="name"><?php echo  $this->form->name->getDecorator('label')->getOption('requiredPrefix').$this->form->name->getLabel(); ?></label>
                <div class="col-sm-8">
                    <?php $this->form->name->setAttrib('container','collapseOptions'); echo $this->form->name->renderViewHelper(); ?>
                    <input type="hidden" id="repeated_banner_name" value="<?php echo $lang->translate('The banner name already exist');?>" />
                </div>
            </div>
        </div>
    </div>

    <div class="row-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">
                <label class="col-sm-4 control-label form_label" for="status"><?php echo  $this->form->status->getLabel(); ?></label>
                    <div class="col-sm-8">
                        <?php $this->form->status->setAttrib('container','collapseOptions'); echo $this->form->status->renderViewHelper(); ?>
                    </div>
            </div>
        </div>
    </div>

    <div class="row-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">
                <label class="col-sm-4 control-label form_label" for="description"><?php echo  $this->form->description->getLabel(); ?></label>
                        <div class="col-sm-8">
                                <?php $this->form->description->setAttrib('container','collapseOptions'); echo $this->form->description->renderViewHelper(); ?>
                        </div>
                </div>
        </div>
    </div>


<!-- banner image -->


<div id="image_container">

<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
				<?php $img_file = 'file_img_1'; ?>
				<?php echo $this->form->$img_file->renderViewHelper(); ?>
				<?php $file = ""; ?>
				<?php if($this->form->$img_file->getValue()): ?>
				<?php 	list($folder,$subfolder,$file) = explode('/',$this->form->$img_file->getValue()); ?>
				<?php endif; ?>											

			<div class="control-group">
				<?php $img = 'img_1'; ?>
				<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Image Banner').':' ?></label>
				<div class="col-sm-8">
					<input type="text" disabled="disabled" id="fileLabel_1" value="<?php echo $file; ?>">
					<?php echo $this->form->$img->renderViewHelper(); ?>
					<p class="help-block grey">(jpg,png,gif,jpeg)</p>
					<input type="hidden" name="hdnNameFile_1" id="hdnNameFile_1" value=""/>
				</div>
			</div>
		</div>
</div>


<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">
                
				<?php $img_prw = 'imageprw_1'; ?>
					<label class="col-sm-4 control-label form_label"><?php echo $this->form->$img_prw->getLabel(); ?></label>
					<div class="col-sm-8">
						<?php echo $this->form->$img_prw->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
					</div>
			</div>
		</div>
</div>

</div>


<!-- banner flash -->


<div id="flash_container">

<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            
				<?php $flash_file = 'file_flash_1'; ?>
				<?php echo $this->form->$flash_file->renderViewHelper(); ?>
				<?php $file = ""; ?>
				<?php if($this->form->$flash_file->getValue()): ?>
				<?php 	list($folder,$subfolder,$file) = explode('/',$this->form->$flash_file->getValue()); ?>
				<?php endif; ?>											
										
			<div class="control-group">
				<?php $flash = 'flash_1'; ?>
				<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Flash Banner').':' ?></label>
				<div class="col-sm-8">
					<input type="text" disabled="disabled" id="fileLabelFlash_1" value="<?php echo $file; ?>">
					<?php echo $this->form->$flash->renderViewHelper(); ?>
					<p class="help-block grey">(swf)</p>
					<input type="hidden" name="hdnNameFileFlash_1" id="hdnNameFileFlash_1" value=""/>
				</div>
			</div>
		</div>
</div>


</div>



<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="col-sm-4 control-label form_label" for="html"><?php echo $this->form->html->getDecorator('label')->getOption('requiredPrefix').$this->form->html->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php $this->form->html->setAttrib('container','collapseOptions'); echo $this->form->html->renderViewHelper(); ?>
					<p class="help-block grey">(<?php echo $lang->translate('HTML code')?>)</p>
				</div>
			</div>
		</div>
</div>
<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="col-sm-4 control-label form_label" for="link"><?php echo $this->form->link->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php $this->form->link->setAttrib('container','collapseOptions'); echo $this->form->link->renderViewHelper(); ?>
					<p class="help-block grey">www.google.com</p>
				</div>
			</div>
		</div>
</div>
<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="required col-sm-4 control-label" for="type"><?php echo  '* '.$lang->translate('Publication Type').':'; ?></label>
				<div class="col-sm-8">
					<div class="btn-group" data-toggle="buttons-radio">
					     <?php foreach($publication_type as $k => $opt): ?>
					    <input type="button" class="btn btn-primary <?php if($this->form->type->getValue()==$k): echo 'active'; endif; ?>" id="publication_type_btn_<?php echo $k; ?>" value="<?php echo $opt; ?>" option="<?php echo $k; ?>">                           
					     <?php endforeach; ?>                       
					    </div>
						<?php $this->form->type->setAttrib('container','collapseCommentsManagement'); echo $this->form->type->renderViewHelper(); ?>
				</div>
			</div>
		</div>
</div>
<div id="dates_container">
<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="col-sm-4 control-label form_label" for="publish_date"><?php echo $this->form->publish_date->getDecorator('label')->getOption('requiredPrefix').$this->form->publish_date->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php echo $this->form->publish_date->renderViewHelper(); ?>
				</div>
			</div>
		</div>
</div>

<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="col-sm-4 control-label form_label" for="expire_date"><?php echo $this->form->expire_date->getDecorator('label')->getOption('requiredPrefix').$this->form->expire_date->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php echo $this->form->expire_date->renderViewHelper(); ?>		
				</div>
			</div>
		</div>
</div>
</div>
<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="col-sm-4 control-label form_label" for="hits"><?php echo $this->form->hits->getDecorator('label')->getOption('requiredPrefix').$this->form->hits->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php echo $this->form->hits->renderViewHelper(); ?>
				</div>
			</div>
		</div>
</div>

<?php if($this->section_list_option!=null){?>
<div class="container-fluid">
        <div id="name_row-fluid" class="col-md-4 col-md-offset-4">
            <div class="form-group">		
				<label class="col-sm-4 control-label form_label" for="sections"><?php echo $this->form->sections->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php echo $this->form->sections->renderViewHelper(); ?>	
				</div>
			</div>
		</div>
</div>
<?php }?>

<div class="row-fluid">
	<?php echo $this->form->id->renderViewHelper(); ?>
</div> 

<input type="hidden" id="btn_value" name="btn_value" value="<?php echo $this->banner_type;?>">
<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">

<div class="row-fluid">
	<div id="save_image_row-fluid" class="row-fluid ">
		<div class="control-group">
			<div class="col-md-12 center">
			
				<button id="save_btn" class="btn btn-success" type="button" name="save_btn">Guardar</button>
			</div>
		</div>
	</div>
</div>


</form>

	<!-- END BANNERS FORM -->
