<?php 
/**
 * Index View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_User_Index
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Diego Perez
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>




<div class="container-fluid option_bar_container line">
	<?php foreach($this->cms_links as $action_id => $opt): ?>
	<?php if($opt['action']=='new'): ?>
	<ul class="nav nav-pills pull-right">
        <li>
            <a  id="new_banner" class="pointer"><?php echo $lang->translate('New Banner'); ?></a>
        </li>
    </ul>
    <?php endif; ?>
    <?php if($opt['action']=='linkbanner'): ?>
    <ul class="nav nav-pills pull-right">
        <li>
            <a  id="link_banner" class="pointer"><?php echo $lang->translate('Link Banner'); ?></a>
        </li>
    </ul>
    <?php endif; ?>
    <?php endforeach; ?>
</div>

<div class="container-fluid line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<?php if ($this->banners_list && count($this->banners_list)>0): ?>

<div class="row-fluid">
	<div class="alert alert-info general_legend_text">
		<div class="legend_inner_left">
			<i class="glyphicon glyphicon-info-sign"></i>
		</div>
		<div class="right">
			<i class="glyphicon glyphicon-pencil"></i> <?php echo $lang->translate('Update'); ?> &nbsp;&nbsp;
			<i class="glyphicon glyphicon-trash"></i> <?php echo $lang->translate('Delete'); ?> &nbsp;&nbsp;
			<i class="glyphicon glyphicon-move"></i> <?php echo $lang->translate('Order'); ?> 
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Banners list'); ?></h1>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	var delete_question = "<?php echo $lang->translate('This banner will be deleted. Would you like to continue?');?>";
</script>
<div class="container-fluid">	
<form action="" class="form-horizontal" method="post" name="frmBannersOrder" id="frmBannersOrder">
	
	<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">
	
	<div class="row table-bordered-header">	
		<div class="col-md-6"><b><?php echo $lang->translate('Banner name'); ?></b></div>
		<div class="col-md-1"><b><?php echo $lang->translate('Order'); ?></b></div>
		<div class="col-md-4 last"><b><?php echo $lang->translate('Tools'); ?></b></div>
	</div>
	
	<div id="sortable">
		<?php foreach ($this->banners_list as $k => $entry): ?> 
		<div class="row table-bordered-content <?php if(($k+1)%2): echo "odd"; endif;?>" id="<?php echo $entry->id; ?>">	
			<div class="col-md-6 pointer"><a class="pointer" id="edit_banner_<?php echo $entry->id;?>" banner_id="<?php echo $entry->id;?>"> <?php echo $entry->name; ?> </a></div>
			<div class="col-md-1 handler move"><i class="glyphicon glyphicon-move"></i></div>			
			<div class="col-md-4 last pointer">
			<?php foreach($this->cms_links as $action_id => $opt): ?>
			<?php if($opt['action']=='edit'): ?>
			<a class="pointer" id="edit_banner_<?php echo $entry->id?>" banner_id="<?php echo $entry->id;?>" title="<?php echo $lang->translate('Update'); ?>"><i class="glyphicon glyphicon-pencil"></i></a> /
			<?php endif; ?>
			<?php if($opt['action']=='delete'): ?>
			<a class="pointer" id="delete_banner_<?php echo $entry->id?>" banner_id="<?php echo $entry->id;?>" title="<?php echo $lang->translate('Delete'); ?>"><i class="glyphicon glyphicon-trash"></i></a>
			<?php endif; ?>
			<?php endforeach; ?>	
			</div>			
		</div>					
		<?php endforeach ?>
	</div>
	<?php if($this->total_sec == $this->assigned_sec): ?>
	<div class="row">
		<input type="hidden" id="banner_order" name="banner_order" value="">
		<input type="hidden" id="identifier" name="identifier" value="banners" />
		<br>  
		<input type="button" id="save_order" name="save_order" class="btn btn-success" value="<?php echo $lang->translate('Save order'); ?>">
	</div>
	<?php endif; ?>
</form>	
</div>
<?php else: ?>	
	<div class="row center">
		<h3><?php echo $lang->translate('No Banners Found'); ?></h3>
		<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">
	</div>	
<?php endif ?>

