<?php $lang = Zend_Registry::get('Zend_Translate'); ?>
<?php //Zend_Debug::dump($lang); ?>
<div class="well center" id="step1_container">
    
    <?php if($this->preview_install==false) {?>
    <form action="#" method="post" name="frmInstallStep1" id="frmInstallStep1">
        <div class="row-fluid line">
            <div class="span12">
                <h2><?php echo $lang->translate('Step').' 1: '.$lang->translate('Choose the installer language');?></h2>
            </div>
        </div>
        <div class="row-fluid line">
            <div class="span12">
                <select name="selLanguage" id="selLanguage">
                    <?php foreach($this->language_list as $k=>$l):?>
                        <option value="<?php echo $k; ?>" <?php if($k==$this->default_lang): echo 'selected="selected"'; endif;?>><?php echo $l; ?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <div class="row-fluid line">
            <div class="pull-right">
              <input type="button" id="step1_next" class="btn btn-primary" name="step1_next" value="<?php echo $lang->translate('Next');?>">
            </div>
        </div>
    </form>
    <?php } elseif($this->preview_install==true) {?>
    <div class="row-fluid line" id="preview_installation_msg">
	    <div class="span4">&nbsp;</div>	
			<div class="span4">
	        	<div class="line-top center bold alert alert-error">
	        		<?php echo $lang->translate('Preview installation was found.');?>
	        		<div><a href="/core/"><?php echo $lang->translate('Click here to go to the WicaWeb administration'); ?></a></div>
	        	</div>
	      	</div>
	    <div class="span4">&nbsp;</div>  
	</div>
	<?php } ?>
</div>

<div id="installer_container">
    
</div>