<?php $lang = Zend_Registry::get('Zend_Translate'); ?>
<?php //Zend_Debug::dump($lang); ?>
<div class="well center container-fluid" id="step1_container">
    
    <?php if($this->preview_install==false) {?>
    <form action="#" class="form-horizontal" method="post" name="frmInstallStep1" id="frmInstallStep1">
        <div class="row">
            <div class="col-md-12">
                <h2><?php echo $lang->translate('Step').' 1: '.$lang->translate('Choose the installer language');?></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <div class="form-group">
                    <select name="selLanguage" class="form-control" id="selLanguage">
                    <?php foreach($this->language_list as $k=>$l):?>
                        <option value="<?php echo $k; ?>" <?php if($k==$this->default_lang): echo 'selected="selected"'; endif;?>><?php echo $l; ?></option>
                    <?php endforeach;?>
                    </select>
                </div>
            </div>
        </div>
        <div class="row-fluid line">
            <div class="pull-right"> 
              <input type="button" id="step1_next" class="btn btn-primary" name="step1_next" value="<?php echo $lang->translate('Next');?>">
            </div>
        </div>
    </form>
    <?php } elseif($this->preview_install==true) {?>
    <div class="row line" id="preview_installation_msg">
	    
            <div class="col-md-4 col-md-offset-4">
                <div class="line-top center bold alert alert-danger">
                        <?php echo $lang->translate('Preview installation was found.');?>
                        <div><a href="/core/"><?php echo $lang->translate('Click here to go to the WicaWeb administration'); ?></a></div>
                </div>
            </div>
	    
	</div>
	<?php } ?>
</div>

<div id="installer_container">
    
</div>