<?php $lang = Zend_Registry::get('Zend_Translate'); ?>
<div class="row-fluid installer_legend_container" id="installer_legend_container_inner">
	<ul class="install_process" id="install_process">
		<li class="header">
			<div class="installer_option">
				<i class="icon-home"></i>
				<span class="step_title"> 
					<b><?php echo $lang->translate('Install Process'); ?></b>
				</span>  
			</div>
		</li>
        <li>
			<div class="installer_option selected" id="opt_step_1">
				<i class="icon-arrow-right icon-white"></i>
				<span class="step_title">
					<b><?php echo '1. '.$lang->translate('Language'); ?></b>
				</span>	  
			</div>
		</li>
        <li>
			<div class="installer_option" id="opt_step_2">
				<i class="icon-minus"></i> 
				<span class="step_title">
					<b><?php echo '2. '.$lang->translate('Welcome Message'); ?></b>
				</span>  
			</div>
		</li>
        <li>
			<div class="installer_option" id="opt_step_3">
				<i class="icon-minus"></i> 
				<span class="step_title">
					<b><?php echo '3. '.$lang->translate('Database Configuration'); ?></b>
				</span>  
			</div>
		</li>
        <li>
			<div class="installer_option" id="opt_step_4">
				<i class="icon-minus"></i> 
				<span class="step_title">
					<b><?php echo '4. '.$lang->translate('Super Admin Configuration'); ?></b>
				</span>  
			</div>
		</li>
		<li>
			<div class="installer_option" id="opt_step_5">
				<i class="icon-minus"></i> 
				<span class="step_title">
					<b><?php echo '5. '.$lang->translate('Website Configuration Type'); ?></b>
				</span>  
			</div>
		</li>
		<li>
			<div class="installer_option" id="opt_step_6">
				<i class="icon-minus"></i> 
				<span class="step_title">
					<b><?php echo '6. '.$lang->translate('Website Configuration'); ?></b>
				</span>  
			</div>
		</li>
	</ul>
</div>