<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

	<div class="row line">
        <div class="col-md-12">
            <h2><?php echo $lang->translate('Step').' 6: '.$lang->translate('Website Configuration');?></h2>
        </div>
     </div>
     	    	
		<!-- BEGIN WEBSITE FORM -->	    
		<div class="row">
			<div class="">
				<form id="<?php echo $this->form->getId() ?>" action="<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod() ?>" class="form-horizontal" enctype="<?php echo $this->form->getAttrib('enctype'); ?>" >
					<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
						<div class="panel panel-default">
                                                    <div class="panel-heading" role="tab" id="headingOption">
                                                        <h4 class="panel-title">
                                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOption" aria-expanded="true" aria-controls="collapseOption">
                                                                1. <?php echo $lang->translate('Option Configuration');?> 
                                                            </a>
                                                        </h4>
                                                    </div>
                                                    <div id="collapseOption" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOption">
                                                        <div class="panel-body">
                                                            <div class="row">
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="name"><?php echo  $this->form->name->getDecorator('label')->getOption('requiredPrefix').$this->form->name->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->name->setAttrib('container','collapseOptions'); echo $this->form->name->renderViewHelper(); ?>
                                                                                            <input type="hidden" id="repeated_website_name" value="<?php echo $lang->translate('The website name already exist');?>" />
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="info_email"><?php echo $this->form->info_email->getDecorator('label')->getOption('requiredPrefix').$this->form->info_email->getLabel(); ?> <i class="glyphicon glyphicon-question-sign" title="<?php echo $lang->translate('Notification mail'); ?>"></i></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->info_email->setAttrib('container','collapseOptions'); echo $this->form->info_email->renderViewHelper(); ?>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                            </div>
                                                            <div class="row">
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="description"><?php echo  $this->form->description->getDecorator('label')->getOption('requiredPrefix').$this->form->description->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->description->setAttrib('container','collapseOptions'); echo $this->form->description->renderViewHelper(); ?>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="copyright"><?php echo $this->form->copyright->getDecorator('label')->getOption('requiredPrefix').$this->form->copyright->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->copyright->setAttrib('container','collapseOptions'); echo $this->form->copyright->renderViewHelper(); ?>
                                                                                    </div>
                                                                            </div>
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="language_id"><?php echo $this->form->language_id->getDecorator('label')->getOption('requiredPrefix').$this->form->language_id->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->language_id->setAttrib('container','collapseOptions'); echo $this->form->language_id->renderViewHelper(); ?>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                            </div>
                                                            <div class="row">
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="keywords"><?php echo  $this->form->keywords->getDecorator('label')->getOption('requiredPrefix').$this->form->keywords->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->keywords->setAttrib('container','collapseOptions'); echo $this->form->keywords->renderViewHelper(); ?>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="icon"><?php echo $this->form->icon->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <div class=" upload_icon_container"> 
                                                                                                    <div class='upload_icon'><?php echo $this->form->icon->removeDecorator('HtmlTag')->removeDecorator('Label'); ?></div>
                                                                                                    <div class='delete_icon'><a id='delete_icon' class="pointer trash-icon"><i class='glyphicon glyphicon-trash'></i></a></div>
                                                                                            </div> 
                                                                                            <p class="help-block grey">(jpg,png,gif,jpeg,ico)</p>
                                                                                    </div>
                                                                            </div>
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-5">&nbsp;</div>
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php echo $this->form->img_icon->removeDecorator('HtmlTag')->removeDecorator('Label'); ?><p id="website_icon"></p>
                                                                                    </div>
                                                                            </div>

                                                                    </div>
                                                            </div>
                                                            <div class="row">
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="website_url"><?php echo $this->form->website_url->getDecorator('label')->getOption('requiredPrefix').$this->form->website_url->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php $this->form->website_url->setAttrib('container','collapseOptions'); echo $this->form->website_url->renderViewHelper(); ?>
                                                                                            <p class="help-block grey">www.google.com</p>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                                    <div class="col-md-6">
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-4 form_label">
                                                                                            <label class="required" for="logo"><?php echo $this->form->logo->getLabel(); ?></label>
                                                                                    </div>
                                                                                    
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php echo $this->form->logo->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
                                                                                            <p class="help-block grey">(jpg,png,gif,jpeg)</p>
                                                                                    </div>
                                                                            </div>
                                                                            <div class="row form-group">
                                                                                    <div class="col-md-5">&nbsp;</div>
                                                                                    <div class="col-md-5 col-md-offset-1 form_field">
                                                                                            <?php echo $this->form->img_logo->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
                                                                                    </div>
                                                                            </div>
                                                                    </div>
                                                            </div>




                                                            <div class="row center">
                                                                    <input type="button" class="btn btn-warning" value="<?php echo $lang->translate('Continue');?>" id="continue_1" current="collapseOption" next="collapseTemplates">
                                                            </div>
                                                        </div>
                                                    </div>
						</div>
						
						
				    	
						<div class="panel panel-default">
                                                    <div class="panel-heading" role="tab" id="headingTwo">
                                                        <h4 class="panel-title">
                                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTemplates" aria-expanded="false" aria-controls="collapseTemplates"> 
                                                                2. <?php echo $lang->translate('Templates');?> 
                                                            </a>
                                                        </h4>
                                                        </div>
                                                        <div id="collapseTemplates" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                                                <div class="panel-body">
                                                                        <div class="row">
                                                                                <div class="center col-md-12">
                                                                                        <?php $this->form->template_id->setAttrib('container','collapseTemplates'); echo $this->form->template_id->renderViewHelper(); ?>
                                                                                </div>
                                                                        </div>

                                                                        <div class="row">
                                                                                <ul id="template_list_options" class="template_list" >
                                                                                        <?php foreach($this->template_list as $template):?>
                                                                                                <li class="template_list center">
                                                                                                        <?php if($template->image):?>
                                                                                                                <img alt="<?php echo $template->name; ?>" src="/uploads/template_img/<?php echo $template->image;?>">
                                                                                                        <?php else:?>
                                                                                                                <div class="no_image">&nbsp;</div>
                                                                                                        <?php endif;?>
                                                                                                        <input type="button" id="template_opt_<?php echo $template->id?>" class="btn btn-primary" template="<?php echo $template->id;?>" value="<?php echo $template->name; ?>">
                                                                                                </li>
                                                                                        <?php endforeach;?>
                                                                                </ul>
                                                                        </div>

                                                                        <div class="row">
                                                                                <div class="col-md-12">
                                                                                        <div class="row center">
                                                                                                <input type="button" class="btn btn-warning" value="<?php echo $lang->translate('Continue'); ?>" id="continue_2" current="collapseTemplates" next="collapseStates">
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                </div>
						
					
						<div class="panel panel-default">
                                                    <div class="panel-heading" role="tab" id="headingStates">
                                                        <h4 class="panel-title">
                                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseStates" aria-expanded="false" aria-controls="collapseStates"> 
                                                                8. <?php echo $lang->translate('Website Status Configuration');?> 
                                                            </a>
                                                        </h4>
                                                        </div>
                                                        <div id="collapseStates" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingStates">
                                                            <div class="panel-body">
                                                                        <div class="row">
                                                                                <div class="col-md-6">
                                                                                        <div class="row form-group">
                                                                                                <div class="col-md-4 form_label">
                                                                                                        <label class="required" for="website_status"><?php echo  $this->form->website_status->getDecorator('label')->getOption('requiredPrefix').$this->form->website_status->getLabel(); ?></label>
                                                                                                </div>
                                                                                                
                                                                                                <div class="col-md-4 form_field ">
                                                                                                        <?php $this->form->website_status->setAttrib('container','collapseStates'); echo $this->form->website_status->renderViewHelper(); ?>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                                <div class="col-md-6">

                                                                                </div>
                                                                        </div>
                                                                        <div class="row">
                                                                                <div class="col-md-6">
                                                                                        <div class="row form-group">
                                                                                                <div class="col-md-4 form_label">
                                                                                                        <label class="required" for="offline_text"><?php echo  $this->form->offline_text->getDecorator('label')->getOption('requiredPrefix').$this->form->offline_text->getLabel(); ?></label>
                                                                                                </div>
                                                                                                
                                                                                                <div class="col-md-4 form_field ">
                                                                                                        <?php $this->form->offline_text->setAttrib('container','collapseStates'); echo $this->form->offline_text->renderViewHelper(); ?>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                                <div class="col-md-6">
                                                                                        <div class="row form-group">
                                                                                                <div class="col-md-4 form_label">
                                                                                                        <label class="required" for="offline_image"><?php echo  $this->form->offline_image->getLabel(); ?></label>
                                                                                                </div>
                                                                                                
                                                                                                <div class="col-md-5 col-md-offset-1 form_field">
                                                                                                        <?php echo $this->form->offline_image->removeDecorator('HtmlTag')->removeDecorator('Label');  ?>
                                                                                                        <p class="help-block grey">(jpg,png,gif,jpeg)</p>
                                                                                                </div>
                                                                                        </div>
                                                                                        <div class="row">
                                                                                                <div class="col-md-5">&nbsp;</div>
                                                                                                <div class="col-md-5 col-md-offset-1 form_field">
                                                                                                        <?php echo $this->form->img_offline->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div class="row">
                                                                                <div class="col-md-6">
                                                                                        <div class="row form-group">
                                                                                                <div class="col-md-4 form_label">
                                                                                                        <label class="required" for="coming_soon_text"><?php echo  $this->form->coming_soon_text->getDecorator('label')->getOption('requiredPrefix').$this->form->coming_soon_text->getLabel(); ?></label>
                                                                                                </div>
                                                                                                
                                                                                                <div class="col-md-4 form_field ">
                                                                                                        <?php $this->form->coming_soon_text->setAttrib('container','collapseStates'); echo $this->form->coming_soon_text->renderViewHelper(); ?>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                                <div class="col-md-6">
                                                                                        <div class="row form-group">
                                                                                                <div class="col-md-4 form_label">
                                                                                                        <label class="required" for="coming_soon_image"><?php echo  $this->form->coming_soon_image->getLabel(); ?></label>
                                                                                                </div>
                                                                                                
                                                                                                <div class="col-md-5 col-md-offset-1 form_field">
                                                                                                        <?php echo $this->form->coming_soon_image->removeDecorator('HtmlTag')->removeDecorator('Label');  ?>
                                                                                                        <p class="help-block grey">(jpg,png,gif,jpeg)</p>
                                                                                                </div>
                                                                                        </div>
                                                                                        <div class="row form-group">
                                                                                                <div class="col-md-5">&nbsp;</div>
                                                                                                <div class="col-md-5 col-md-offset-1 form_field">
                                                                                                        <?php echo $this->form->img_coming_soon->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                </div>
					</div>
				</form>				
			</div>
			<div class="row-fluid">
				<div class="center well">
					<div class="pull-left">
			          <input type="button" id="step6_back" class="btn btn-primary" name="step6_back" value="<?php echo $lang->translate('Back');?>">
			        </div>
					<div class="row-fluid">
						<?php echo $this->form->submit->renderViewHelper(); ?>
					</div>
				</div>
			</div>
	</div>	    	
	<!-- END WEBSITE FORM -->