<?php 
/**
 * ControlPanel View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_Index_ControlPanel
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<div class="row-fluid line">
	<div class="span12 page-header-wica center">
		<h1> <?php echo $lang->translate('Cliente Home');?> </h1>
	</div>
</div>
<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="well">
	<div class="row-fluid">
            <div class="span12">
                UD. Se encuentra en mora
            </div>
		<ul id="control_panel_options" class="nav nav-pills">
			<?php foreach($this->menu_modules as $module):?>
				<li class="control_panel_opt">
                                    <a id="<?php echo $module?>" class="pointer center"><?php if($module):?>
                                        <img alt="<?php echo $lang->translate($module);?>" src="/images/controlPanel/<?php echo $module;?>" class="control_panel_image">
                                            <?php endif;?>
                                        <br>
                                                <?php echo $lang->translate($module);?>
                                    </a>
                                </li>       
			<?php endforeach;?>
		</ul>
	</div>	
</div>