<!-- 
 *	View that contains a section form to create a new element
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.01
 * @author	   David Rosales, Jose Luis Landazuri
 -->

<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<script type="text/javascript" charset="utf-8">
	var next_step = "<?php echo $lang->translate('Continue');?>";
	var back_step = "<?php echo $lang->translate('Back');?>";
	var max_size = "<?php echo $lang->translate('Maximum size');?>";
	var supported_extension = "<?php echo $lang->translate('Supported files');?>";
</script>
		

<div class="row-fluid line">
	<div class="span12">
		<div class="page-header-wica center">
			<h1><?php if($this->parent_section):?> <?php echo $lang->translate('New subsection'); ?> <?php echo $this->parent_section['title']; ?> <?php else: ?> <?php echo $lang->translate('New section'); ?>   <?php endif;?></h1>		
		</div>
	</div>	
</div>

<div class="row-fluid line">
	<div class="span12"></div>	
</div>

<div class="row-fluid">
	<div class="span4 center">&nbsp;</div>
	<div class="span4 center">
		<div class="btn-group">
			<input type="button" class="btn btn-primary" id="bar_step_beg" value="<?php echo $lang->translate('Basic');?>">
			<?php if($this->website_db->section_images_number !=0): ?>
			<input type="button" class="btn btn-primary wizard_step_bar" value="<?php echo $lang->translate('Images');?>">
			<?php endif; ?>
			<?php if($this->website_db->section_expiration =='yes'): ?>
			<input type="button" class="btn btn-primary wizard_step_bar" value="<?php echo $lang->translate('Publication dates');?>">
			<?php endif; ?>
			<?php if($this->website_db->section_author =='yes' || $this->website_db->private_section =='yes' || $this->website_db->section_feature =='yes' || $this->website_db->section_highlight =='yes' || $this->website_db->section_comments =='section' || $this->website_db->section_rss =='yes'): ?>
			<input type="button" class="btn btn-primary wizard_step_bar" value="<?php echo $lang->translate('Additional setup');?>">
			<?php endif; ?>
		</div>
	</div>
</div>	

<div class="row-fluid line">
	<div class="span12">
		&nbsp;
	</div>	
</div>

<form class="well <?php echo $this->form->getAttrib('class'); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" method="<?php echo $this->form->getMethod(); ?>" enctype="multipart/form-data">
<?php 	$confirm_options = GlobalFunctions::arrayTranslate(Core_Model_Section::$confirm); 
		$type_options = GlobalFunctions::arrayTranslate(Core_Model_Section::$section_type);	?>
		
<div class="row-fluid">
	<div class="span12">					
		<!-- BASIC SECTION CONFIG -->
		<div class="step_containers">
			<div class="row-fluid">
				<div class="span6">
					<div class="row-fluid">							
						<?php echo $this->form->id->renderViewHelper(); ?>	      							      			
						<?php echo $this->form->section_parent_id->renderViewHelper(); ?>
						<?php echo $this->form->section_temp->renderViewHelper(); ?>
		      		 	<div class="control-group">
							<label class="control-label"><?php echo $this->form->section_template_id->getLabel(); ?></label>
							<div class="controls">
								<?php echo $this->form->section_template_id->renderViewHelper(); ?>									
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><?php echo $this->form->title->getLabel(); ?></label>
							<div class="controls">
								<?php echo $this->form->title->renderViewHelper(); ?>										
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><?php echo $this->form->internal_name->getLabel(); ?></label>
							<div class="controls">
								<?php echo $this->form->internal_name->renderViewHelper(); ?>								
							</div>
							<input type="hidden" id="repeated_section_name" value="<?php echo $lang->translate('The internal name of content already exist');?>" />
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><?php echo $this->form->subtitle->getLabel(); ?></label>
							<div class="controls">
								<?php echo $this->form->subtitle->renderViewHelper(); ?>									
							</div>
						</div>	
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><?php echo $this->form->title_browser->getLabel(); ?></label>
							<div class="controls">
								<?php echo $this->form->title_browser->renderViewHelper(); ?>								
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><?php echo $this->form->keywords->getLabel(); ?></label>
							<div class="controls">
								<?php echo $this->form->keywords->renderViewHelper(); ?>													
							</div>
						</div>
					</div>
	      		</div>				      		
	      		<div class="span6">				      							      		
	      			<div class="control-group">
						<label class="control-label"><?php echo $this->form->synopsis->getLabel(); ?></label>
						<div class="controls">
							<?php echo $this->form->synopsis->renderViewHelper(); ?>
						</div>
					</div>
	      		</div>				      		
			</div>	
					
			<div class="row-fluid">					
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo '* '.$lang->translate('External link').':'; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">
								<?php $default_link_arr = array_keys($confirm_options);
									$default_link_opt = $default_link_arr[1]; ?>							
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_link_opt == $k): echo 'active'; endif; ?>" id="link-<?php echo $k; ?>" value="<?php echo $opt; ?>">
								<?php endforeach; ?>
							</div>
							<?php echo $this->form->link->renderViewHelper(); ?>
						</div>
					</div>
				</div>
			</div>
			
			<div class="row-fluid hide" id="link_container">
				<div class="span6">
					<div class="control-group">
						<label class="control-label"><?php echo $this->form->external_link->getLabel(); ?></label>
						<div class="controls">
							<?php echo $this->form->external_link->renderViewHelper(); ?>								
						</div>
					</div>	
				</div>			
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo '* '.$lang->translate('Target').':'; ?></label>
						<div class="controls">						
							<div class="btn-group" data-toggle="buttons-radio">
								<?php $target_type = GlobalFunctions::arrayTranslate(Core_Model_Section::$target_type); ?>
								<?php foreach($target_type as $k => $opt): ?>
								<input type="button" class="btn btn-primary" id="target_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>
							<?php echo $this->form->target->renderViewHelper(); ?>													
						</div>
					</div>		
				</div>
			</div>
			
			<div class="row-fluid">
				<div class="span6">									
	      		 	<div class="control-group">
						<label class="control-label"><?php echo '* '.$lang->translate('Area').':'; ?></label>
						<div class="controls">						
							<select id="area" name="area">
								<option value=""><?php echo $lang->translate('Selected'); ?></option>
								<?php foreach ($this->template_areas as $ky => $tpl ): ?>
								<option value="<?php echo $tpl->id; ?>" type="<?php echo $tpl->type; ?>" <?php if($tpl->area_number == 1):?> selected="selected" <?php endif; ?>><?php echo $tpl->name; ?></option>
								<?php endforeach; ?>
	 						</select>
						</div>
						<?php echo $this->form->section_area->renderViewHelper(); ?> 					
					</div>																							
	      		</div>
	     		 
                            
	      		
                       <div class="span6" id="menus">
                            <?php echo $this->form->parent_show_menu->renderViewHelper(); ?>
                            <div class="span6" id="menu_opt_container">	
                                            <div class="control-group">
                                                    <label class="control-label"><?php echo '* '.$lang->translate('Show in menu').':'; ?></label>
                                                    <div class="controls">
                                                            <div class="btn-group" data-toggle="buttons-radio">
                                                                    <?php $default_area_arr = array_keys($confirm_options);
                                                                            $default_area_opt = $default_area_arr[0]; ?>
                                                                    <?php foreach($confirm_options as $k => $opt): ?>
                                                                    <input type="button" class="btn btn-primary" id="menu-<?php echo $k; ?>" value="<?php echo $opt; ?>">							
                                                                    <?php endforeach; ?>							
                                                            </div>
                                                            <?php echo $this->form->menu->renderViewHelper(); ?> <?php //if($default_area_opt == $k): echo 'active'; endif; ?> 																		
                                                    </div>
                                            </div>	
                                    </div>
                            
                            
                            <?php echo $this->form->parent_show_menu2->renderViewHelper(); ?>
                            <div class="span6" id="menu2_opt_container">	
                                            <div class="control-group">
                                                    <label class="control-label"><?php echo '* '.$lang->translate('Show in menu').':'; ?> 2</label>
                                                    <div class="controls">
                                                            <div class="btn-group" data-toggle="buttons-radio">
                                                                    <?php $default_area_arr = array_keys($confirm_options);
                                                                            $default_area_opt = $default_area_arr[0]; ?>
                                                                    <?php foreach($confirm_options as $k => $opt): ?>
                                                                    <input type="button" class="btn btn-primary" id="menu2-<?php echo $k; ?>" value="<?php echo $opt; ?>">							
                                                                    <?php endforeach; ?>							
                                                            </div>
                                                            <?php echo $this->form->menu2->renderViewHelper(); ?> <?php //if($default_area_opt == $k): echo 'active'; endif; ?> 																		
                                                    </div>
                                            </div>	
                                    </div>
                            </div>
                        </div>    
			
			<div class="row-fluid">			      		
	      		<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo '* '.$lang->translate('Set as homepage').':'; ?> <?php if(count($this->section_act)>0): ?> <i class="icon-question-sign" title="<?php echo $lang->translate('Actual homepage').': '.$this->section_act->title; ?>"></i><?php endif; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">
								<?php $default_homepage_arr = array_keys($confirm_options);
									$default_homepage_opt = $default_homepage_arr[1]; ?>								
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_homepage_opt == $k): echo 'active'; endif; ?>" id="homepage-<?php echo $k; ?>" value="<?php echo $opt; ?>">
								<?php endforeach; ?>							
							</div>
							<?php echo $this->form->homepage->renderViewHelper(); ?>
						</div>
					</div>	
				</div>				      		      						      		
			</div>
		</div>		
		
		<!-- SECTION FIELDS ACCORDING WEBSITE CONFIG -->
		<!-- section images -->
		<?php if($this->website_db->section_images_number !=0): ?>
			<div class="step_containers">
		<?php for ($i=1; $i<=$this->website_db->section_images_number ;$i++){ ?>
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">										
					<div class="control-group">
						<?php $img = 'img_'.$i; ?>
						<label class="control-label"><?php echo $lang->translate('Image').' '.$i.':' ?></label>
						<div class="controls">
							<input type="text" disabled="disabled" id="fileLabel_<?php echo $i; ?>">
							<?php echo $this->form->$img->renderViewHelper(); ?>
							<input type="hidden" name="hdnNameFile_<?php echo $i; ?>" id="hdnNameFile_<?php echo $i; ?>" value=""/>
						</div>
					</div>
					<div class="control-group">
						<?php $img_name = 'name_img_'.$i; ?>
						<label class="control-label"><?php echo $this->form->$img_name->getLabel(); ?></label>
						<div class="controls">
							<?php echo $this->form->$img_name->renderViewHelper(); ?>
						</div>
					</div>
					<div class="control-group">
						<?php $img_prw = 'imageprw_'.$i; ?>
						<label class="control-label"><?php echo $this->form->$img_prw->getLabel(); ?></label>
						<div class="controls">
							<?php echo $this->form->$img_prw->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
						</div>
					</div>
					<?php $img_file = 'file_img_'.$i; ?>
					<?php echo $this->form->$img_file->renderViewHelper(); ?>
																
					<?php $img_id = 'id_img_'.$i; ?>
					<?php echo $this->form->$img_id->renderViewHelper(); ?>
				</div>
			</div>
		<?php } ?>
			</div>
	 	<?php endif; ?>
			
		<!-- publication dates -->
		<?php if($this->website_db->section_expiration =='yes'): ?>	
		<div class="step_containers">			
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $this->form->publish_date->getLabel(); ?></label>
                                                <div class="controls">
							<?php echo $this->form->publish_date->renderViewHelper(); 
                                                        ?>
						</div>
					</div>
				</div>				
			</div>			
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $this->form->expire_date->getLabel(); ?></label>
						<div class="controls">
							<?php echo $this->form->expire_date->renderViewHelper();
                                                        
                                                        ?>									
						</div>
					</div>
				</div>
			</div>			
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $lang->translate('Show publish date').':'; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">	
								<?php $default_publish_arr = array_keys($confirm_options);
									$default_publish_opt = $default_publish_arr[1]; ?>						
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_publish_opt == $k): echo 'active'; endif; ?>" id="btn_publish_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>					
							<?php echo $this->form->show_publish_date->renderViewHelper(); ?>
						</div>
					</div>	
				</div>						
			</div>			
		</div>
		<?php else: ?>
		<div class="row-fluid">
			<?php echo $this->form->publish_date->renderViewHelper(); ?>
			<?php echo $this->form->expire_date->renderViewHelper(); ?>
			<?php echo $this->form->show_publish_date->renderViewHelper(); ?>			
		</div>
		<?php endif; ?>
		
		<!-- other setup -->	
		<?php if($this->website_db->section_author =='yes' || $this->website_db->private_section =='yes' || $this->website_db->section_feature =='yes' || $this->website_db->section_highlight =='yes' || $this->website_db->section_comments =='section' || $this->website_db->section_rss =='yes'): ?>
		<div class="step_containers">
		<?php endif; ?>
			<?php if($this->website_db->section_author =='yes'): ?>		
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $this->form->author->getLabel(); ?></label>
						<div class="controls">
							<?php echo $this->form->author->renderViewHelper(); ?>								
						</div>
					</div>	
				</div>						
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->author->renderViewHelper(); ?>
			</div>
			<?php endif; ?>
			
			<?php if($this->website_db->private_section =='yes'): ?>		
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $lang->translate('Section type').':'; ?></label>
						<div class="controls">						
							<div class="btn-group" data-toggle="buttons-radio">
								<?php $default_type_arr = array_keys($type_options);
									$default_type_opt = $default_type_arr[0]; ?>		
								<?php $type_options = GlobalFunctions::arrayTranslate(Core_Model_Section::$section_type); ?>
								<?php foreach($type_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_type_opt == $k): echo 'active'; endif; ?>" id="type_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>					
							<?php echo $this->form->type->renderViewHelper(); ?>			
						</div>
					</div>	
				</div>						
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->type->renderViewHelper(); ?>
			</div>
			<?php endif; ?>
					
			<?php if($this->website_db->section_feature =='yes'): ?>		
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $lang->translate('Feature').':'; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">	
								<?php $default_feature_arr = array_keys($confirm_options);
									$default_feature_opt = $default_feature_arr[1]; ?>							
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_feature_opt == $k): echo 'active'; endif; ?>" id="feature_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>
							<?php echo $this->form->feature->renderViewHelper(); ?>
						</div>
					</div>	
				</div>						
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->feature->renderViewHelper(); ?>			
			</div>
			<?php endif; ?>
			
			<?php if($this->website_db->section_highlight =='yes'): ?>		
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $lang->translate('Highlight').':'; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">	
								<?php $default_highlight_arr = array_keys($confirm_options);
									$default_highlight_opt = $default_highlight_arr[1]; ?>							
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_highlight_opt == $k): echo 'active'; endif; ?>" id="highlight_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>		
							<?php echo $this->form->highlight->renderViewHelper(); ?>
						</div>
					</div>	
				</div>						
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->highlight->renderViewHelper(); ?>			
			</div>
			<?php endif; ?>
			
			<?php if($this->website_db->section_comments =='section'): ?>		
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $lang->translate('Comments').':'; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">								
								<?php $default_comments_arr = array_keys($confirm_options);
									$default_comments_opt = $default_comments_arr[1]; ?>
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_comments_opt == $k): echo 'active'; endif; ?>" id="comments_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>		
							<?php echo $this->form->comments->renderViewHelper(); ?>													
						</div>
					</div>	
				</div>						
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->comments->renderViewHelper(); ?>			
			</div>
			<?php endif; ?>				
			
			<?php if($this->website_db->section_rss =='yes'): ?>		
			<div class="row-fluid">
				<div class="span4"> &nbsp; </div>
				<div class="span6">	
					<div class="control-group">
						<label class="control-label"><?php echo $lang->translate('RSS').':'; ?></label>
						<div class="controls">
							<div class="btn-group" data-toggle="buttons-radio">								
								<?php $default_rss_available_arr = array_keys($confirm_options);
									$default_rss_opt = $default_rss_available_arr[1]; ?>
								<?php foreach($confirm_options as $k => $opt): ?>
								<input type="button" class="btn btn-primary <?php if($default_rss_opt == $k): echo 'active'; endif; ?>" id="rss_<?php echo $k; ?>" value="<?php echo $opt; ?>">							
								<?php endforeach; ?>							
							</div>	
							<?php echo $this->form->rss_available->renderViewHelper(); ?>												
						</div>
					</div>	
				</div>						
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->rss_available->renderViewHelper(); ?>			
			</div>
			<?php endif; ?>
			
			<?php if($this->website_db->publication_approve =='yes'): ?>		
			<div class="row-fluid">
				<?php echo $this->form->approved->renderViewHelper(); ?>
				<?php echo $this->form->publication_status->renderViewHelper(); ?>
			</div>
			<?php else: ?>
			<div class="row-fluid">
				<?php echo $this->form->approved->renderViewHelper(); ?>
				<?php echo $this->form->publication_status->renderViewHelper(); ?>
			</div>
			<?php endif; ?>
			
			<div class="row-fluid">
				<?php echo $this->form->section_images->renderViewHelper(); ?>			
			</div>
		<?php if($this->website_db->section_author =='yes' || $this->website_db->private_section =='yes' || $this->website_db->section_feature =='yes' || $this->website_db->section_highlight =='yes' || $this->website_db->section_comments =='section' || $this->website_db->section_rss =='yes'): ?>
		</div>
		<?php endif; ?>
	</div>
</div>
</form>

<div class="row-fluid">
	<div class="center well">
		<div class="row-fluid">					
			<?php echo $this->form->submit_button->renderViewHelper(); ?>
			&nbsp;&nbsp;
			<?php echo $this->form->cancel_button->renderViewHelper(); ?>		
		</div>
	</div>
</div>
