<?php
/**
 * View that contains the results of a search
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @version    1.0
 * @author	   Esteban
 */

//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<div class="row-fluid line">
	<div class="span12 page-header-wica center">
		<h1><?php echo $lang->translate('Search Sections')?></h1>
	</div>
</div>

<div class="row-fluid">
	<div class="span12 line">
		<h3><?php echo $lang->translate('Search Parameters')?>: <?php echo $this->section_search_params;?></h3>		 
	</div>
</div>

<?php if($this->section_results && count($this->section_results)>0):?>
	<div class="row-fluid">
		<table class="table table-bordered">
			<tr>
				<th> <?php echo $lang->translate('Internal name');?> </th>
				<th> <?php echo $lang->translate('Title');?> </th>			
				<th> <?php echo $lang->translate('Synopsis');?> </th>
			</tr>
			<?php foreach ($this->section_results as $section):?>
			<tr>
				<td>
					<a id="edit_section_<?php echo $section->id; ?>" class="pointer" editable_section="<?php echo $section->editable_section; ?>" section_id="<?php echo $section->id; ?>" section_parent="<?php echo $section->section_parent_id; ?>" temp="<?php echo $section->temp; ?>"><?php echo $section->internal_name;?></a>					
				</td>
				<td><?php echo $section->title;?></td>			
				<td><?php echo $section->synopsis;?></td>
			</tr>	
			<?php endforeach;?>
		</table>
	</div>
<?php else:?>
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No Sections Found');?></h3>
	</div>
<?php endif;?>
