<!-- 
 *	View that contains a list of available sections by website 
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php echo $this->flashMessages();?>

<?php if (count($this->section)>0): ?>
	<div class="control-group">
		<label class="control-label" for="optionsCheckbox"><b><?php echo $lang->translate('Total control'); ?></b></label>
		<div class="controls">
			<label class="checkbox">
				<input type="checkbox" name="total_control" id="section_<?php echo $this->website_id; ?>">							
			</label>
		</div>
	</div>

	<?php foreach ($this->section as $k => $entry): ?>
	<div class="control-group">
		<label class="control-label" for="optionsCheckbox"><?php echo $entry->title;?></label>
		<div class="controls">
			<label class="checkbox">
				<input type="checkbox" name="section[<?php echo $entry->id; ?>][section]" nick="<?php echo $entry->title;?>" parent="<?php echo $this->website_id;?>" id="section_<?php echo $this->website_id.'_'.$entry->id; ?>">							
			</label>
		</div>
	</div>    
  <?php endforeach ?>   
  <input type="hidden" id="website_id" value="<?php echo $this->website_id; ?>"/>	
<?php endif ?>


