<!-- 
 *	Section preview
 *
 * @category   WicaWeb
 * @package    Core_Partial
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 <?php
 $lang = Zend_Registry::get('Zend_Translate');
 
 $section_contents_tpl = array();
 
 foreach($this->areas as $area)
 {
 	$section_contents_tpl[$area->name] = '&nbsp;'; 
 }
 
 foreach($this->section_contents as $section => $key)
 {
 	$render = ""; 	
 	$aux_sectemplate = fopen(APPLICATION_PATH."/modules/default/views/scripts/partials/".$key['filename'], "r");
 	if($aux_sectemplate)
 	{
 		//Output a line of the file until the end is reached
 		while(!feof($aux_sectemplate))
 		{
 			$render.= fgets($aux_sectemplate);
 		}
 		fclose($aux_sectemplate);
 		
 		if($render)
 		{
	 		//last find of previewHelper
	 		$search = 'previewHelper(';
	 		$pos_occ = strpos($render, $search);
	 		if($pos_occ)
	 		{
	 			$beg_part = substr($render, 0, ($pos_occ + strlen($search)));
	 			//next part of string after previewHelper(
	 			$render_part = substr($render, $pos_occ);
	 			//then find ,
	 			$pos_grt = strpos($render_part, ',');
	 			//next part of string after ,
	 			$render_part = substr($render_part, ($pos_grt+1));	 			
	 			$render = $beg_part.$render_part;
	 		}
	 		
	 		//adding columns for space and alignment 
	 		$search = 'mov_content_';
	 		//last find of content_container
 			$pos_occ = strpos($render, $search);
 			if($pos_occ)
 			{
 				//next part of string after content_container
 				$render_part = substr($render, $pos_occ);
 				//then find ">
 				$pos_grt = strpos($render_part, '">');
 				//next part of string after ">
 				$render_part = substr($render_part, $pos_grt);
 				//then find <
 				$pos_lss = strpos($render_part, '<');
 				//next part of string after <
 				$render_part = substr($render_part, $pos_lss);
 					
 				$view = substr_replace($render, '<div class="row"> <div class="col-md-12" id="alignment_container_<?php echo $value["content_id"]; ?>"> <?php echo $value["alignment_fields"]; ?> </div> </div>', ($pos_occ+$pos_grt+2));
 				$view.= $render_part;
 				$render = $view;
 			}
 			 		
	 		foreach($key['content'] as $k => $content){
	 		$nav_container = ' 
				<ul class="nav tools_list_container">
		    		<li class="dropdown tools_list">
					    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="cols_container_'.$content['content_id'].'" title="'.$lang->translate("Columns").'">
						   <i class="glyphicon glyphicon-th-list"></i>
	 						<span id="cols_value_'.$content['content_id'].'">';
					   		$aux_count=1;  
					   			  while($aux_count <= $key['column_number'])
					   			  {
					   					if($aux_count== $content['columns']){
					   						$nav_container.= $aux_count;
					   					}
					   			  		$aux_count++; 
					   			  }
					   			 	
			$nav_container.= '</span>
						   <b class="caret"></b>
					    </a>
					    <ul class="dropdown-menu cols_tools_list">';
					    	$aux_count=1;
					    		  while($aux_count <= $key['column_number']){ 
					    			$nav_container.= '<li><a id="opt_cols_'.$aux_count.'" class="pointer" val="'.$aux_count.'" content_id="'.$content['content_id'].'">'.$aux_count.'</a></li>';
					    			 $aux_count++; 
					    			}
					    				
			$nav_container.= '</ul>
					 </li>
					    	<li class="dropdown tools_list">
					    		<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="align_container_'.$content['content_id'].'" title="'.$lang->translate("Align").'">
					    			<i class="glyphicon glyphicon-resize-horizontal"></i>
					    			<span id="align_value_'.$content['content_id'].'">';
					    			switch($content['align'])
					    			{
					    				case "left":
					    					$nav_container.= $lang->translate("Left");
					    					break;
					    				case "center":
					    					$nav_container.= $lang->translate("Center");
					    					break;
					    				case "right":
					    					$nav_container.= $lang->translate("Right");
					    					break;
					    			}
				$nav_container.= '</span>
					    			<b class="caret"></b>
					    		</a>
					    		<ul class="dropdown-menu align_tools_list">
    								<li><a id="opt_align_left" class="pointer" val="left" content_id="'.$content['content_id'].'">'.$lang->translate("Left").'</a></li>
    								<li><a id="opt_align_center" class="pointer" val="center" content_id="'.$content['content_id'].'">'.$lang->translate("Center").'</a></li>
    								<li><a id="opt_align_right" class="pointer" val="right" content_id="'.$content['content_id'].'">'.$lang->translate("Right").'</a></li>
    							</ul>
					    	</li>
					    </ul>
					    <input type="hidden" id="columns_content_'.$content['content_id'].'" name="columns_content_'.$content['content_id'].'" value="'; 
						if($content['align']){ 
							$nav_container.= $content['columns']; 
						}else{
							$nav_container.= '1'; 
						}
					    $nav_container.= '" />';
					    $nav_container.= '<input type="hidden" id="align_content_'.$content['content_id'].'" name="align_content_'.$content['content_id'].'" value="';
					    if($content['align']){
					    	$nav_container.= $content['align']; 
					    }else{ 
					    	$nav_container.= ""; 
	 					}
					     $nav_container.= '" />';

	 			$key['content'][$k]['alignment_fields'] = $nav_container;						 					 		
 			}	 		
	 	}
 		
	 	$sectemplate = fopen(APPLICATION_PATH."/modules/core/views/scripts/partials/section_template.phtml", "r");
	 	if($sectemplate)
	 	{ 	
	 		fwrite($sectemplate, $render); 	
	 		fclose($sectemplate);
	 	}
		
		//session storage vals
		$session_render_vals = new Zend_Session_Namespace('render_vals');
		$session_render_vals->area_width = $key['area_width'];
		$session_render_vals->section_cols = $key['column_number'];
		
	 	$html_content = $this->partial("partials/section_template.phtml", array('contents' => $key['content'], 'articles' => null, 'col_number' => $key['column_number'], 'section_title' => $key['section_title'], 'section_subtitle' => $key['section_subtitle']));
	 	
	 	//delete session storage
	 	Zend_Session::namespaceUnset('render_vals');
	 	
	 	if($html_content)
	 	{
	 		$html_content.= ' <input type="hidden" id="section_sel" value="'.$key['area'].'">';
	 		$section_contents_tpl[$key['area']] = $html_content;
	 	}
 	}
 }

 $section_preview = '';
 
 if(count($section_contents_tpl)>0)
 {
 	$render_tpl = $this->templaterender;
 	
 	if($render_tpl)
 	{
 		foreach ($section_contents_tpl as $key => $section_content)
 		{
 			$view = '';
 			if($section_content)
 			{
 				//last find of section_name
 				$pos_occ = strpos($render_tpl, $key);
 				if($pos_occ)
 				{
 					//next part of string after are_name as id
 					$render_part = substr($render_tpl, $pos_occ);
 					//then find >
 					$pos_grt = strpos($render_part, '>');
 					//next part of string after >
 					$render_part = substr($render_part, $pos_grt);
 					//then find </
 					$pos_lss = strpos($render_part, '</');
 					//next part of string after </
 					$render_part = substr($render_part, $pos_lss);
 						
 					$view = substr_replace($render_tpl, $section_content, ($pos_occ+$pos_grt+1));
 					$view.= $render_part;
 					$render_tpl = $view;
 				}
 			}
 		}

 		$save_button_1 = '';
 		$save_button_2 = '';
 		
 		foreach($this->cms_links as $action_id => $opt){
	 		if($opt['action']=='edit'){
	 			$save_button_1 = '<input type="button" id="save_content_order_prw_1" name="save_content_order_prw_1" class="btn btn-success" value="'.$lang->translate('Save changes').'">'; 
	 			$save_button_2 = '<input type="button" id="save_content_order_prw_2" name="save_content_order_prw_2" class="btn btn-success" value="'.$lang->translate('Save changes').'">';
	 		}	 		
 		}

 		//creating submit and cancel button
 		$render_tpl = '<form action="#" method="post" name="frmPreviewContentOrder" id="frmPreviewContentOrder">
 		<div class="row-fluid" align="center">
 		'.$save_button_1.'
 		<input type="button" id="cancel_content_order_prw_2" name="cancel_content_order_prw_2" class="btn" value="'.$lang->translate('Cancel').'">
 		</div>'.$render_tpl;
 		
 		$render_tpl.= '
 		<div class="row-fluid" align="center">&nbsp;</div>
 		<div class="row-fluid" align="center">
 		<input type="hidden" id="preview_content_order" name="preview_content_order" value="" />
 		'.$save_button_2.'
 		<input type="button" id="cancel_content_order_prw_2" name="cancel_content_order_prw_2" class="btn" value="'.$lang->translate('Cancel').'">
 		</div>
 		</form>';
 		
 		$section_preview =  $render_tpl; 		
 	}
 }
 ?>
 
 <?php echo $section_preview; ?>
 