<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php
	$id = New Zend_Session_Namespace('id');
	$website_name_info = $id->website_name_info; 
?>

<ul class="sections_selector_tree" id="sections_selector_tree">
	<li>
		<div class="parent_section">
			<a id="section_selector_0" class="pointer" section_id="">
				<i class="icon-home"></i> <b><?php echo $lang->translate('Main section'); ?></b>
			</a>
		</div>
	</li>
	<?php echo $this->sections; ?>
</ul>
