<!-- 
 *	View that contains a list of available sections by website 
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php echo $this->flashMessages();?>

<?php if (count($this->section)>0): ?>
        <div class="form-group">
            <label class="col-md-12">
                <p class="col-sm-8 control-label form_label " for="optionsCheckbox"><b><?php echo $lang->translate('Total control'); ?></b></p>
                <div class="col-sm-4 checkbox">
                    <input type="checkbox" name="total_control" id="section_<?php echo $this->website_id; ?>">							
                </div>
            </label>
        </div>
        <?php foreach ($this->section as $k => $entry): ?>
        <div class="form-group">
            <label class="col-md-12">
                <p class="col-sm-8 control-label form_label " for="optionsCheckbox"><?php echo $entry->title;?></p>
                <div class="col-sm-4 checkbox">
                    <input type="checkbox" name="section[<?php echo $entry->id; ?>][section]" nick="<?php echo $entry->title;?>" parent="<?php echo $this->website_id;?>" id="section_<?php echo $this->website_id.'_'.$entry->id; ?>">
                </div>
            </label>
        </div> 
  <?php endforeach ?>   
  <input type="hidden" id="website_id" value="<?php echo $this->website_id; ?>"/>	
<?php endif ?>


