<!-- 
 *	View that contains a list of sections to be ordered 
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->

<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<?php if (count($this->section)>0): ?>

<div class="row-fluid">
	<div class="alert alert-info general_legend_text">
		<div class="legend_inner_left">
			<i class="icon-info-sign"></i>
		</div>
		<div class="right">
			<i class="icon-pencil"></i> <?php echo $lang->translate('Update'); ?> &nbsp;&nbsp;
			<i class="icon-trash"></i> <?php echo $lang->translate('Delete'); ?> &nbsp;&nbsp;
			<i class="icon-move"></i> <?php echo $lang->translate('Order'); ?> 
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Section list'); ?></h1>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	var delete_question = "<?php echo $lang->translate('All section info and its contents will be deleted. Would you like to continue?');?>";
</script>
	
<form action="#" method="post" name="frmSectionsOrder" id="frmSectionsOrder">
	<div class="row-fluid table-bordered-header">	
		<div class="span6"><b><?php echo $lang->translate('Section name'); ?></b></div>
		<div class="span1"><b><?php echo $lang->translate('Order'); ?></b></div>
		<div class="span4 last"><b><?php echo $lang->translate('Tools'); ?></b></div>
	</div>
	
	<div id="sortable">
		<?php foreach ($this->section as $k => $entry): ?> 
		<div class="row-fluid table-bordered-content <?php if(($k+1)%2): echo "odd"; endif;?>" id="<?php echo $entry->temp.'_'.$entry->id; ?>">	
			<div class="span6 pointer"><a id="tree_<?php echo $entry->id; ?>" article="<?php echo $entry->article; ?>" editable_section="<?php echo $entry->editable_section; ?>" temp="<?php echo $entry->temp; ?>"> <?php echo $this->escape($entry->title); ?> </a></div>
			<div class="span1 handler move"><i class="icon-move"></i></div>			
			<div class="span4 last pointer">
				<?php if($entry->editable_section=='yes'): ?>
					<a id="edit_section_<?php echo $entry->id; ?>" temp="<?php echo $entry->temp; ?>" editable_section="<?php echo $entry->editable_section; ?>" section_id="<?php echo $entry->id; ?>" article="<?php echo $entry->article; ?>" title="<?php echo $lang->translate('Update'); ?> "><i class="icon-pencil"></i> </a>/
				<?php endif; ?>
				<?php if($entry->erasable_section=='yes'): ?>
					<a id="delete_section_<?php echo $entry->id; ?>" title="<?php echo $lang->translate('Delete'); ?>"><i class="icon-trash"></i> </a>
				<?php endif; ?>				
			</div>			
		</div>					
		<?php endforeach ?>
	</div>
	<?php if($this->total_sec == $this->assigned_sec): ?>
	<div class="row-fluid">
		<input type="hidden" id="section_order" name="section_order" value="">
		<input type="hidden" id="identifier" name="identifier" value="sections" />
		<br>  
		<input type="button" id="save_order" name="save_order" class="btn btn-success" value="<?php echo $lang->translate('Save order'); ?>">
	</div>
	<?php endif; ?>
</form>	
<?php else: ?>	
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No Sections Available'); ?></h3>
	</div>	
<?php endif ?>