<!-- 
 *	View that contains a content form to update an object
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   Santiago Arellano
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<div class="row">
    <div class="col-md-12">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Edit '.$this->content_type.' Content'); ?> <?php if($this->section_data):?> <?php echo $lang->translate( 'of').' '.$this->section_data['title']; ?> <?php endif; ?> </h1>
	</div>
    </div>
</div>

<div class="row">
<div id="div_content" class="col-md-6"  style="z-index:5; position: relative;">
	<?php echo $this->flashMessages(); ?>
<!-- 	Form -->	
	<form class="well form-horizontal <?php echo $this->form->getAttrib('class'); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" method="<?php echo $this->form->getMethod(); ?>" enctype="multipart/form-data">		
	<!-- 	Get elements from post -->
		<?php foreach($this->form->getElements() as $name => $element){ 
//                        echo $name;
//                        echo '<br>';
                    ?>
			<?php if(strpos($name, 'hdnNameFile')=== false){ ?>		
				<div class="row">
				<!-- 				Div only for separate elements -->
				
				
				<div id="<?php echo $name."_row-fluid";?>" class="col-md-12 <?php if(($this->form->$name->helper == 'formHidden' || $this->form->$name->class == 'hide') && ($name!='flash_file' && $name!='alternative_image' && $name!='aux_make_div_image' && $name!='select_images' && $name != 'background' && $name != 'type' && $name != 'captcha' && $name != 'target'  && $name != 'resizeimg' && $name!='watermarkimg')){ echo 'hide'; }?> ">
			<?php if($name == 'select_images'){ ?>                                  
                                    <div class="form-group">
                                       <label id="carrusel_images_order" class="col-sm-3 control-label control-label-edit<?php if( ($this->form->$name->class == 'hide' || $this->form->$name->class == 'hide btn') && ($name != 'alternative_image' && $name != 'flash_file')) echo ' hide'?>"><?php if($name == 'file' || $name == 'alternative_image' || $name == 'flash_file'){ echo 'Orden Actual:'; }else{ echo 'Orden Actual:'; }?></label>
                                       <div class="col-sm-9">
                                            <div id="sortable_header" class="row" style="background-color:#B9B9B9; ">
                                                <div class="col-md-3"><b><?php echo '#'; ?></b></div>
                                                <div class="col-md-3"><b><?php echo 'Imagen'; ?></b></div>
                                                <div class="col-md-3 center"><b><?php echo 'Mover'; ?></b></div>
                                                <div class="col-md-3"><b><?php echo 'Herramientas'; ?></b></div>
                                            </div>
                                           <div id="sortable" class="row" >
                                            <?php foreach ($this->images as $k=>$img):?>
                                            <div id="<?php echo $img; ?>" style="border: 1px solid #000000; border-style: dashed;" class="row-fluid">
                                                <div class="col-md-3"><?php echo $k; ?></div>
                                                <div class="col-md-3"><img src="<?php echo '../uploads/content/'.$img; ?>" width="100%"> </div>
                                                <div class="col-md-3 center"><a class="pointer" ><i class="glyphicon glyphicon-move"></i></a></div>
                                                <div class="col-md-3 center"><a class="pointer"><i id="delete_<?php echo $img; ?>" class="glyphicon glyphicon-trash"></i></a></div>
                                            </div>
                                            <?php endforeach;?>
                                        </div>
                                           </div>
                                           
                                        <input type="hidden" id="images_order" name="images_order" value="" />
                                        <input type="hidden" id="deleted_images" name="deleted_images" value="" />	
                                    </div>        
                          <?php } ?>	


						<div class="form-group">
<!-- 						Control when label should be show -->						
						<?php if(($this->form->$name->helper != 'formSubmit' && $this->form->$name->helper != 'formButton') || ($name == 'file' || $name == 'alternative_image' || $name == 'flash_file')) { ?>
							<label id="<?php echo $name."_label"?>" class="col-sm-3 control-label control-label-edit<?php if( ($this->form->$name->class == 'hide' || $this->form->$name->class == 'hide btn') && ($name != 'alternative_image' && $name != 'flash_file')) echo ' hide'?>"><?php if($name == 'file' || $name == 'alternative_image' || $name == 'flash_file'){ echo $this->form->$name->label_name;  }else{ echo $this->form->$name->getLabel(); }?></label>
                                                        <div class="col-md-9 <?php if($this->form->$name->helper == 'formButton') echo 'center';?>">
                                                <?php }else{ ?>
                                                        <div class="col-md-12 <?php if($this->form->$name->helper == 'formButton') echo 'center';?>">
                                                <?php } ?>	
                                                        
							
					
								<?php 
// 								Div for carrusel multi image uploader								
									if($name == 'select_images'){
										?>
											<div id='multiple_img'></div>
											<p class="help-block grey">(jpg,png,gif,jpeg)</p>
										<?php
									}else//Div for single image upload
										if($name == 'aux_make_div_image'){?>
												<div id='single_img' >
												</div>
												<p class="help-block grey">(jpg,png,gif,jpeg)</p>
												<?php
										}	
										else	
// 											Build blue special buttons to replace radio button elements
                                                                                    
											if($name == 'background' || $name == 'type' || $name == 'captcha' || $name == 'target'  || $name == 'resizeimg' || $name=='watermarkimg'){ 
													$static_var = $name.'_values'; ?>
													<div class="btn-group" data-toggle="buttons-radio">
														<?php foreach ( Core_Model_Content::$$static_var as $k => $entry): ?>
														<input type="button" class="btn btn-primary"  id="<?php echo $name.'-'.$k; ?>" name="<?php echo $name.'-'.$k; ?>" element_value="<?php echo $k; ?>" value="<?php echo $lang->translate($this->escape($entry)); ?>" />							
														<?php endforeach; ?>							
													</div>	
                                                                                                     <?php echo $this->form->$name->renderViewHelper();
                                                                                                       
                                                                                           if($name=='watermarkimg'){
                                                                                  ?>
                                                                                        <br>
                                                                                        <label class="col-sm-3 control-label control-label-edit" id="watermark_position_label">Position</label>
                                                                                       <br>
                                                                                       <div class="col-sm-8">
                                                                                            
                                                                                            <input type="button" pos="TL" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_TL">
                                                                                            <input type="button" pos="T" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_T">
                                                                                            <input type="button" pos="TR" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_TR"> <br>
                                                                                            <input type="button" pos="L" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_L">
                                                                                            <input type="button" pos="C" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_C">
                                                                                            <input type="button" pos="R" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_R"> <br>
                                                                                            <input type="button" pos="BL" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_BL">
                                                                                            <input type="button" pos="B" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_B">
                                                                                            <input type="button" pos="BR" value="" class="btn btn-default watermark_pos_selector" id="wmk_pos_BR">
                                                                                        </div>
                                                                                       
                                                                                  <?php
                                                                                        echo $this->form->watermark_position->renderViewHelper();
                                                                                               
                                                                                           }           
                                                                                                       
											}
											else
                                                                                                
// 												Extructure for file uploads												
												if($name == 'file' || $name == 'alternative_image' || $name=='flash_file'){?>
                                                                                       <div class="row">
                                                                                                <input class="align-top hide col-md-2" readonly type="text" id="<?php echo 'input_file_'.$name;?>" name="<?php echo 'input_file_'.$name;?>"/>
                                                                                                <?php $this->form->$name->class="hide btn align-top"; echo $this->form->$name->renderViewHelper(); ?>
                                                                                                <?php $hdn_name='hdnNameFile_'.$name; echo $this->form->$hdn_name->renderViewHelper(); ?>

                                                                                                <?php if($name == 'flash_file'){ ?>
                                                                                                        <p class="help-block grey">(swf)</p>
                                                                                                <?php }?>														

                                                                                                <?php if($name == 'alternative_image'){ ?>
                                                                                                        <p class="help-block grey">(jpg,png,gif,jpeg,ico)</p>
                                                                                                        <img id="<?php echo 'imageprw_'.$name; ?>" name="<?php echo 'imageprw_'.$name; ?>" src="" class="preview_img" />												

                                                                                                <?php }?>

                                                                                        </div>
		
												<?php }
												else		
// 													center buttons	
                                                                                                                    //echo $this->form->$name->helper;
													if($this->form->$name->helper == 'formSubmit'){
														//generate save button to print at the end
														$saveButton =  '<div class="row"><div class="col-md-12 center">'.$this->form->$name->renderViewHelper().'</div></div>';
													}elseif($this->form->$name->helper == 'formButton'){
														if($this->form->$name->getName() == 'save_image'){
															//generate save button to print at the end
															$saveButton =  '<div class="row"><div class="col-md-12 center">'.$this->form->$name->renderViewHelper().'</div></div>';
														}else{
                                                                                                                    $saveButton =  '<div class="row"><div class="col-md-12 center">'.$this->form->$name->renderViewHelper().'</div></div>';
															echo '<div class="row"><div class="col-md-12 center">'.$this->form->$name->renderViewHelper().'</div></div>';
														}
													}else
														if($name == 'url'){
															echo $this->form->$name->removeDecorator('HtmlTag')->removeDecorator('Label');
															?>
															<?php 
														}
														else{
															if($name == 'alternative_image')	
																$this->form->$name->class = '';
		
															echo $this->form->$name->removeDecorator('HtmlTag')->removeDecorator('Label');
															if($name == 'content'){
																?> <input type="hidden" name="hdn_content" id="hdn_content" value="" /> <?php
															}
														}
								?>
                                                                                                                                
							</div>
							
							<input type="hidden" id="repeated_section_name" value="<?php echo $lang->translate('The internal name of content already exist');?>" />
		
						</div>	
								
				</div>	
<!-- 				info youtube video -->				
							<?php if($name == 'url'){
									?>
									<br/><div class="col-md-5">
											<img class="col-md-2" id="img_youtube" name="img_youtube" src="" width="200px"/>
											<div class="col-md-4">
												<div id="title_youtube" ></div>
												<div id="url_youtube" ></div>
								                <div id="description_youtube" style="text-align:justify;"></div>
											</div>
										</div><br/>
									<?php 
								}?>					
				</div>	
				<?php if($name == 'add'){ ?>
					<div class="row-fluid">											
						<div id='form_elements' class="row-fluid center line"></div>
						<div id='div_hidden_elements'></div>						
					</div>
				<?php } ?> 
			<?php } ?>
		<?php } 
		//prints the save button at the end
		if($this->content_type=='Image'||$this->content_type=='Carousel'){
		echo $saveButton;
                }
		?>
                <div id="deleted_array" style="visibility:hidden"></div>
		<input type="hidden" id="approved" name="approved" value="<?php echo $this->approved_frm; ?>" />		
		<input type="hidden" id="section_details" name="section_details" value="<?php echo $this->section_id.'/'.$this->article;?>" />
		<input type="hidden" id="section_temp" name="section_temp" value="<?php echo $this->section_temp; ?>" />
		<input type="hidden" id="hdn_max_height_img" name="hdn_max_height_img" value="<?php echo $this->max_height; ?>" />
		<input type="hidden" id="hdn_max_width_img" name="hdn_max_width_img" value="<?php echo $this->max_width; ?>" />		
	</form>
	

	<a id="anchor_add" class="hide" href="#formContent"></a>
	<div style="display: none">
	<!-- form of elments on content form -->
		<div id="formContent">
			
		</div>

	</div>	
	
	<input type="hidden" id="hdn_content_id" name="hdn_content_id" value="<?php echo $this->content_id; ?>" />
	
	<!-- table header of form elements -->
	<input id="header_table" type="hidden" value='<?php echo '<label id="labl_no_elements"><h4>'.$lang->translate('No items entered').'</h4></label>
															<div id="elements_table" class="hide">
																<div class="row-fluid table-bordered-header">
																	<div class="col-md-4"><b>'.$lang->translate('Name').'</b></div>
																	<div class="col-md-2"><b>'.$lang->translate('Type').'</b></div>
																	<div class="col-md-2"><b>'.$lang->translate('Order').'</b></div>
																	<div class="col-md-3 last"><b>'.$lang->translate('Tools').'</b></div>
																</div>
															</div>
															<div id="sortable" class="hide"></div>'?>' /> 
															
            <input type="hidden" id="repeat_content" value="<?php echo $lang->translate('The internal name of content already exist');?>" />
            <input type="hidden" id="content_id" value="<?php echo $this->content_id;?>" />
</div>

<?php if($this->preview){
		//session storage vals
		$session_render_vals = new Zend_Session_Namespace('render_vals');
		$session_render_vals->area_width = "col-md-12";
		$session_render_vals->section_cols = 1;
		$session_render_vals->edit_preview = 'yes';
?>

<!-- preview column -->
<div  class="col-md-6" style="z-index:1; position: relative;">	
	<div  id="div_preview" class="well">
		<h3><?php echo $lang->translate('Current Content'); ?></h3><br><br>
	
		<?php echo $this->previewHelper($this->preview); ?>
		
	</div>
</div>	
<?php	Zend_Session::namespaceUnset('render_vals'); 
	 }?>	
</div>
<!-- flash player message -->
<div id="no_flash_player" class="row-fluid hide center">
	<label><b><?php echo $lang->translate("Your browser does not have Flash Player installed or activated"); ?></b></label><br/>
	<img src="/images/flash_player.jpg" width="80px;">
</div>