<!-- 
 *	View that contains a list of available contents
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   Santiago Arellano
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate');?>

<div class="row">
    <div class="col-md-12">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Contents');?></h1>
	</div>
    </div>
</div> 
<div class="row">
    <div class="col-md-12">
        <?php echo $this->flashMessages();?>
    </div>
</div> 

<?php if (count($this->content_type)>0): ?>
<div class="row center line">
	<div class="col-md-12 center">
		<div class="btn-group" data-toggle="buttons-radio">							
			<?php foreach ($this->content_type as $k => $entry): ?>
			<input type="button" class="btn btn-primary" content_type_id="<?php echo $entry->id; ?>" id="content_type<?php echo $entry->id; ?>" name="content_type<?php echo $entry->id; ?>"  value="<?php echo $lang->translate($this->escape($entry->name)); ?>" />							
			<?php endforeach; ?>							
		</div>		
	</div>	
	
	<div class="col-md-5 center">&nbsp;</div>
</div>

<div class="row line">
    <div class="col-md-12" id="content_container">
    </div>
</div>

<?php endif ?>
