<?php 
/**
 * Index View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_User_Index
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Diego Perez
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<?php foreach($this->dictionary_links as $action_id => $opt): ?>
<?php if($opt['action']=='new'): ?>
<div class="row-fluid option_bar_container">
	<ul class="nav nav-pills pull-right">
        <li>
            <a href="/core/dictionary_dictionary/new"><?php echo $lang->translate('New Dictionary'); ?></a>
        </li>
    </ul>
</div>
<?php endif; ?>
<?php endforeach; ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="row-fluid center">
	<div class="col-md-12 page-header-wica">
    	<h1> <?php echo $lang->translate('Dictionary List');?> </h1>
	</div>    
</div>
<?php 

if($this->dictionary && count($this->dictionary)>0):?>
 <div class="row-fluid">
     <table class="table table-bordered table-bordered-wica">
		<tr>
			<th> <?php echo $lang->translate('Name');?> </th>
			<th> <?php echo $lang->translate('Status');?> </th>
			<th> <?php echo $lang->translate('Tools');?> </th>
		</tr>
		<?php foreach ($this->dictionary as $k=>$dictionary):?>
		<tr class="<?php if(($k+1)%2): echo "odd"; endif;?>">
			<td><?php echo $dictionary->name;?></td>
			<td><?php echo $lang->translate($dictionary->status);?></td>
			<td>
				<?php foreach($this->dictionary_links as $action_id => $opt): ?>
				<?php if($opt['action']=='edit'): ?>
				<a href='/core/dictionary_dictionary/edit?id=<?php echo $dictionary->id;?>' title="<?php echo $lang->translate('Update'); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
				<?php endif; ?>
				<?php endforeach; ?>	
			</td>
		</tr>	
		<?php endforeach;?>
	</table>
 </div>
<?php else:?>
	 <div class="row-fluid center">
		<h3><?php echo $lang->translate('No Dictionaries Found');?></h3>
	 </div>
	 	<div class="row-fluid center">
				<a class="btn btn-success btn-large" href="/core/dictionary_dictionary/new"><?php echo $lang->translate('New Dictionary'); ?></a>
		</div>
<?php endif;?>
</div>