<?php 
/**
 * Index View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_Website_Index
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<?php foreach($this->external_files_links as $action_id => $opt): ?>
<?php if($opt['action']=='new'): ?>
<div class="row-fluid option_bar_container">
	<ul class="nav nav-pills pull-right">
        <li>
            <a href="/core/externalfiles_externalfiles/new"><?php echo $lang->translate('Add New File'); ?></a>
        </li>
    </ul>
</div>
<?php endif; ?>
<?php endforeach; ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="row-fluid">
	<div class=" page-header-wica span12 center line">
		<h1> <?php echo $lang->translate('Upload External Files');?> </h1>
	</div>
</div>

<div class="row-fluid">
<?php if($this->files && count($this->files)>0):?>
	<form action="#" method="post" name="frmExternalFiles" id="frmExternalFiles">
		<?php if($this->external_files_js && count($this->external_files_js)>0):?>
			<div class="row-fluid center line">
				<h3> <?php echo $lang->translate('Js Files');?> </h3>
			</div>
			<div class="row-fluid table-bordered-header">	
				<div class="span4"><b><?php echo $lang->translate('Name'); ?></b></div>
				<div class="span1"><b><?php echo $lang->translate('Type'); ?></b></div>
				<div class="span4"><b><?php echo $lang->translate('File'); ?></b></div>
				<div class="span1"><b><?php echo $lang->translate('Order'); ?></b></div>
				<div class="span2 last"><b><?php echo $lang->translate('Tools'); ?></b></div>
			</div>
			
			<div id="sortable_js" class="line">    
				<?php foreach ($this->external_files_js as $k => $extfile_js): ?> 
				<div class="row-fluid table-bordered-content <?php if(($k+1)%2): echo "odd"; endif;?>" id="<?php echo $extfile_js->id; ?>">	
					<div class="span4"><?php echo $this->escape( $extfile_js->name); ?></div>
					<div class="span1"><?php echo $extfile_js->type?></div>
					<div class="span4"><?php echo $extfile_js->path;?></div>
					<div class="span1 handler move"><i class="icon-move"></i></div>
					<div class="span2 last pointer">
						<?php foreach($this->external_files_links as $action_id => $opt): ?>
							<?php if($opt['action']=='delete'): ?>
							<a href="/core/externalfiles_externalfiles/remove?id=<?php echo $extfile_js->id;?>" title="<?php echo $lang->translate('Delete'); ?>" onclick="return confirm('Desea eliminar el archivo?')"><i class="icon-trash"></i></a>
							<?php endif; ?>
						<?php endforeach; ?>
						/
						<a href="/core/externalfiles_externalfiles/view?id=<?php echo $extfile_js->id;?>" title="<?php echo $lang->translate('View'); ?>"><i class="icon-indent-left"></i></a>
					</div>			
				</div>					
				<?php endforeach; ?>
			</div>
		<?php endif;?>
		
		<?php if($this->external_files_css && count($this->external_files_css)>0):?>
			<div class="row-fluid center line">
				<h3> <?php echo $lang->translate('Css Files');?> </h3>
			</div>
			<div class="row-fluid table-bordered-header">	
				<div class="span4"><b><?php echo $lang->translate('Name'); ?></b></div>
				<div class="span1"><b><?php echo $lang->translate('Type'); ?></b></div>
				<div class="span4"><b><?php echo $lang->translate('File'); ?></b></div>
				<div class="span1"><b><?php echo $lang->translate('Order'); ?></b></div>
				<div class="span2 last"><b><?php echo $lang->translate('Tools'); ?></b></div>
			</div>
			
			<div id="sortable_css">    
				<?php foreach ($this->external_files_css as $k2 => $extfile_css): ?> 
				<div class="row-fluid table-bordered-content <?php if(($k2+1)%2): echo "odd"; endif;?>" id="<?php echo $extfile_css->id; ?>">	
					<div class="span4"><?php echo $this->escape( $extfile_css->name); ?></div>
					<div class="span1"><?php echo $extfile_css->type?></div>
					<div class="span4"><?php echo $extfile_css->path;?></div>
					<div class="span1 handler move"><i class="icon-move"></i></div>
					<div class="span2 last pointer">
						<?php foreach($this->external_files_links as $action_id => $opt): ?>
							<?php if($opt['action']=='delete'): ?>
								<a href="/core/externalfiles_externalfiles/remove?id=<?php echo $extfile_css->id;?>" title="<?php echo $lang->translate('Delete'); ?>" onclick="return confirm('Desea eliminar el archivo?')"><i class="icon-trash"></i></a>
							<?php endif; ?>
						<?php endforeach; ?>
						/
						<a href="/core/externalfiles_externalfiles/view?id=<?php echo $extfile_css->id;?>" title="<?php echo $lang->translate('View'); ?>"><i class="icon-indent-left"></i></a>
					</div>			
				</div>					
				<?php endforeach; ?>
			</div>
		<?php endif;?>
		
		
		<div class="row-fluid">
			<input type="hidden" id="js_order" name="js_order" value="">
			<input type="hidden" id="css_order" name="css_order" value="">
			<br>  
			<input type="button" id="save_order" name="save_order" class="btn btn-success" value="<?php echo $lang->translate('Save order'); ?>">
		</div>		
	</form>	
<?php else:?>
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No External Files Available Yet');?></h3>
	</div>
<?php endif;?>
</div>