<?php 
/**
 * New View. Renders the view of the New action 
 *
 * @category   WicaWeb
 * @package    Core_View_Externalfile_New
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
$confirm = GlobalFunctions::arrayTranslate(Core_Model_Externalfiles::$confirm);
$website = new Core_Model_Website();
$website_list = $website->find('wc_website');
?>
<script type="text/javascript" src="/js/modules/core/externalfiles/edit_file.js"></script>
<div class="row-fluid line">
	<div class="col-md-12 page-header-wica center line">
		<h1><?php echo $lang->translate('View External File');?></h1>
	</div>
</div>

<div class="row-fluid">
	<div class="col-md-12">
        <?php echo $this->flashMessages();?>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
    	<div class="row-fluid">
	    	<div class="col-md-3">&nbsp;</div>
	    	<div class="col-md-6 well">
	    		<h2 class="center"><?php echo $lang->translate('File Content').': '. $this->file_name;?></h2>
                        <form method="POST" action="/core/externalfiles_externalfiles/editfile?id=<?php echo $this->id ?>" style="margin-bottom: 0;">
                            <textarea id="code" name="code">
                                <?php
                                        foreach($this->file_content as $f):
echo $f;
                                        endforeach;
                                ?>
                            </textarea>
                            <div class="center" style="margin-top: 15px;">
                                <input id="save" class="btn btn-primary" type="submit" value="Save" name="save">
                                <input id="cancel" class="btn btn-primary" type="button" value="Cancel" name="cancel">
                            </div>
                        </form>
	       </div>
	       <div class="col-md-3">&nbsp;</div>
	      </div>
    </div>
</div>
<script type="text/javascript">
        var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
            lineNumbers: true,
            styleActiveLine: true,
            matchBrackets: true,
            lineWrapping: true
        });
</script>