<?php 
/**
 * New View. Renders the view of the New action 
 *
 * @category   WicaWeb
 * @package    Core_View_Externalfile_New
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
$confirm = GlobalFunctions::arrayTranslate(Core_Model_Externalfiles::$confirm);
$website = new Core_Model_Website();
$website_list = $website->find('wc_website');
?>
<div class="row-fluid line">
	<div class="span12 page-header-wica center line">
		<h1><?php echo $lang->translate('View External File');?></h1>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
        <?php echo $this->flashMessages();?>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
    	<div class="row-fluid">
	    	<div class="span3">&nbsp;</div>
	    	<div class="span6 well">
	    		<h2 class="center"><?php echo $lang->translate('File Content').': '. $this->file_name;?></h2>
		       <?php 
			       foreach($this->file_content as $f):
			       		echo $f.'<br/>';
			       endforeach;
		       ?>
	       </div>
	       <div class="span3">&nbsp;</div>
	      </div>
    </div>
</div> 