<!-- 
 *	View that contains articles' contents
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<?php if($this->info):?>
<div class="row-fluid">
	<div class="page-header">
		<h1><?php echo $this->info['title']; ?><span style="font-size: 12px;">
                        (<a target="_blank" href="<?php echo $this->website_id != 1 ? '/site/'.$this->website_id.'/':'/';?>article/<?php echo $this->info['id']; echo '/'.strtolower(GlobalFunctions::formatFilename($this->info['title']));?>">
                            <?php echo $this->website_id != 1 ? '/site/'.$this->website_id.'/':'/';?>article/<?php echo $this->info['id']; echo '/'.strtolower(GlobalFunctions::formatFilename($this->info['title']));?>
                        </a>)</span>
                </h1>
		<span>
			<?php foreach($this->cms_links as $action_id => $opt): ?>
				<?php if($opt['action']=='edit'): ?>
					<a id="edit_article_<?php echo $this->info['id']; ?>" temp="<?php echo $this->info['temp']; ?>" class="pointer"> <i class="glyphicon glyphicon-pencil"></i> </a>
				<?php endif; ?>
				<?php if($opt['action']=='delete'): ?>
					<a id="delete_article_<?php echo $this->info['id']; ?>" temp="<?php echo $this->info['temp']; ?>" class="pointer"> <i class="glyphicon glyphicon-trash"></i> </a>
				<?php endif; ?>
			<?php endforeach; ?>
			<?php if(count($this->contents)>0):?>
					<a id="article_preview_<?php echo $this->info['id']; ?>" class="pointer" title="<?php echo $lang->translate('Preview'); ?>"> <i class="glyphicon glyphicon-eye-open"></i> </a>					
					<a id="article_prw" class="hide" href="#article_front_container"></a>
			<?php endif; ?>
                        <?php if($this->website_data[0]->prints == 'yes'){ 
				//Get prints of actual section
				$section_prints_aux = new Core_Model_SectionPrints();
				$section_prints = $section_prints_aux->find('wc_section_prints',array('section_id'=>$this->info['id']));
				if(count($section_prints)>0){
					echo $lang->translate('Prints').': '.$section_prints[0]->count;
				}else
				{
					echo $lang->translate('Prints').': 0';
				}
				
			}?>                                        
		</span>
	</div>	
	<input type="hidden" id="article_id" name="article_id" value="<?php echo $this->info['id']; ?>">
	<input type="hidden" id="section_parent_id" name="section_parent_id" value="<?php echo $this->info['section_parent_id']; ?>">
</div>

<div class="row-fluid">
	<div class="alert alert-info general_legend_text">
		<div class="legend_inner_left">
			<i class="glyphicon glyphicon-info-sign"></i>
		</div>
		<div class="right">
			<i class="glyphicon glyphicon-pencil"></i> <?php echo $lang->translate('Update'); ?> &nbsp;&nbsp;
			<i class="glyphicon glyphicon-trash"></i> <?php echo $lang->translate('Delete'); ?> &nbsp;&nbsp;
			<i class="glyphicon glyphicon-move"></i> <?php echo $lang->translate('Order'); ?> 
		</div>
	</div>
</div>
<?php endif;?>

<div class="row-fluid hide">
	<div id="article_front_container" class="row-fluid"></div>
</div>

<?php if(count($this->contents)>0):?>
<div class="row-fluid">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Content list'); ?></h1>
	</div>
</div>

<form action="#" method="post" name="frmContentOrder" id="frmContentOrder">
	<div class="row-fluid">
		<div>
			<div class="row-fluid table-bordered-header">	
				<div class="col-md-3"><b><?php echo $lang->translate('Content'); ?></b></div>
				<div class="col-md-1"><b><?php echo $lang->translate('Type'); ?></b></div>
				<div class="col-md-3"><b><?php echo $lang->translate('Internal name'); ?></b></div>
				<div class="col-md-1"><b><?php echo $lang->translate('Order'); ?></b></div>
				<div class="col-md-4 last"><b><?php echo $lang->translate('Actions'); ?></b></div>
			</div>
		</div>
		<div id="content_sortable" class="line">
		<?php foreach ($this->contents as $key => $content): ?>
			<div class="row-fluid table-bordered-content <?php if($key%2==0)echo 'odd'; else echo 'even';?>" id="<?php echo $content['temp'].'_'.$content['id']; ?>">			
				<div class="col-md-3 content_field_list" <?php if($content['type'] != 'Image'): ?> id="<?php echo 'edit_content_'.$content['id']; ?>" content_id="<?php echo $content['id']; ?>" <?php endif; ?>>
					<?php echo GlobalFunctions::getContentPreviewForList($content);?>
				</div>
				<div class="col-md-1 content_field_list"><i class="<?php echo GlobalFunctions::getContentIcons(strtolower($content['type'])); ?>"></i></div>
				<div class="col-md-3 content_field_list"><?php echo utf8_encode($content['internal_name']); ?></div>
				<div class="col-md-1 content_field_list handler move"><i class="glyphicon glyphicon-move"></i></div>
				<div class="col-md-4 content_field_list last visible pointer"> 
					<div class="pull-left no-border">
						<?php foreach($this->cms_links as $action_id => $opt): ?>
							<?php if($opt['action']=='edit'): ?>
								<a id="<?php echo 'edit_content_'.$content['id']; ?>" content_id="<?php echo $content['id']; ?>" section_id="<?php echo $this->info['id']; ?>" > <i class="glyphicon glyphicon-pencil"></i> </a>
								/
							<?php endif; ?>
			    			<?php if($content['serial_cbs']): ?>
				    			<?php if($opt['action']=='delete'): ?>				    						    			
				    			<a id="<?php echo 'erase_content_'.$content['id']; ?>" content_id="<?php echo $content['id']; ?>" content_by_sec="<?php echo $content['serial_cbs']; ?>" temp="<?php echo $content['temp'] ?>"> <i class="glyphicon glyphicon-trash"></i> </a>
				    			/
				    			<?php endif;?>
			    			<?php endif;?>			    			
			    		<?php endforeach; ?>
				    </div>
                                    <div class="pull-left no-border">
				    	<ul class="nav tools_list_container">
				    		<li class="dropdown tools_list">
							    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="cols_container_<?php echo $content['id'];?>" title="<?php echo $lang->translate('Columns'); ?>">
								   <i class="glyphicon glyphicon-th-list"></i>
								   <span id="value_cols_<?php echo $content['id'];?>">
								   		<?php $aux_count=1;  
								   			  while($aux_count<=$this->columns){
								   					if($aux_count==$content['column_number']){
								   						echo  $aux_count;
								   					}
								   			  $aux_count++; }?>	
								   </span>
								   <b class="caret"></b>
							    </a>
							    <ul class="dropdown-menu cols_tools_list">
							    	<?php $aux_count=1;
							    		  while($aux_count<=$this->columns){ ?>
							    			<li><a id="cols_<?php echo $aux_count;?>" class="pointer" val="<?php echo $aux_count;?>" content_id="<?php echo $content['id'];?>"><?php echo $aux_count;?></a></li>
							    	<?php $aux_count++; }?>
							    </ul>
						    </li>
						    <li class="dropdown tools_list">
							    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="align_container_<?php echo $content['id'];?>" title="<?php echo $lang->translate('Align'); ?>">
								   <i class="glyphicon glyphicon-resize-horizontal"></i>
								   <span id="value_align_<?php echo $content['id'];?>">
								   		<?php switch($content['align']){
								   			case "left":
								   				echo $lang->translate('Left');
								   				break;
							   				case "center":
							   					echo $lang->translate('Center');
							   					break;
						   					case "right":
						   						echo $lang->translate('Right');
						   						break;
								   		}?>
								   </span>
								   <b class="caret"></b>
							    </a>
							    <ul class="dropdown-menu align_tools_list">
							    	<li><a id="align_opt_left" class="pointer" val="left" content_id="<?php echo $content['id'];?>"><?php echo $lang->translate('Left');?></a></li>
							    	<li><a id="align_opt_center" class="pointer" val="center" content_id="<?php echo $content['id'];?>"><?php echo $lang->translate('Center');?></a></li>
							    	<li><a id="align_opt_right" class="pointer" val="right" content_id="<?php echo $content['id'];?>"><?php echo $lang->translate('Right');?></a></li>
							    </ul>
						    </li>
						 </ul>				    	
						<input type="hidden" id="<?php echo 'content_columns_'.$content['id']; ?>" name="<?php echo 'content_columns_'.$content['id']; ?>" value="<?php if($content['id']): echo $content['column_number']; else: echo "1"; endif; ?>" />
						<input type="hidden" id="<?php echo 'content_align_'.$content['id']; ?>" name="<?php echo 'content_align_'.$content['id']; ?>" value="<?php if($content['align']): echo $content['align']; else: echo ""; endif; ?>" />
					</div>
				</div>
			</div>
		<?php endforeach; ?>	
		</div>
		
		<div class="row-fluid">
			<div class="alert alert-info general_legend_text">
				<div class="legend_inner_left">
					<i class="glyphicon glyphicon-info-sign"></i>
				</div>
				<div class="right">
					<i class="glyphicon glyphicon-text-size"></i> <?php echo $lang->translate('Text'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-picture"></i> <?php echo $lang->translate('Image'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-link"></i> <?php echo $lang->translate('Link'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-list-alt"></i> <?php echo $lang->translate('Form'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-play-circle"></i> <?php echo $lang->translate('Flash'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-facetime-video"></i> <?php echo $lang->translate('Flash Video'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-film"></i> <?php echo $lang->translate('Carousel'); ?> &nbsp;&nbsp;
					<span class="legend_separator">&nbsp;</span>&nbsp;&nbsp;
					<i class="glyphicon glyphicon-th-list"></i> <?php echo $lang->translate('Columns'); ?> &nbsp;&nbsp;
					<i class="glyphicon glyphicon-resize-horizontal"></i> <?php echo $lang->translate('Align'); ?>
				</div>
			</div>
		</div>
		
		<div class="row-fluid">
			<input type="hidden" id="content_order" name="content_order" value="" />
			<input type="hidden" id="identifier" name="identifier" value="contents" />
			<input type="hidden" id="content_owner" name="content_owner" value="article" />
			<br>  
			<input type="button" id="save_content_order" name="save_content_order" class="btn btn-success" value="<?php echo $lang->translate('Save order'); ?>">
		</div>
	</div>
</form>	
<?php else:?>	
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No Content Available'); ?></h3>
	</div>	
<?php endif;?>
