<!-- 
 *	View that contains a section contents
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	  Carla Fernández
 -->
 <style>
     .row-fluid{
         width: 99%!important
     }
     #article_sortable{
         min-width: 350px;
     }
 </style>
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<div class="line-top alert_messages_container">
		<?php echo $this->flashMessages();?>
</div>

<div class="row-fluid hide">
	<div class="row-fluid" id="front_container"></div>
</div>
<div class="row-fluid">
	<div class="page-header-wica center">
		<h1>Artículos</h1>
	</div>
</div>
<?php 

if($this->articles > 0):?>

<div class="row-fluid">
<form action="#" method="post" name="frmArticlesOrder" id="frmArticlesOrder">
     <div class="row-fluid">
            <input type="hidden" id=section_order name="section_order" value="">
	    <input type="hidden" id="identifier" name="identifier" value="<?php echo $this->typeArticle; ?>" />
            <input type="hidden" id="idArticle" name="idArticle" value="<?php echo $this->idArticle; ?>" />
		<br>  
		<input type="button" id="save_article_order" name="save_article_order" class="btn btn-success" value="<?php echo $lang->translate('Save order'); ?>">
	</div>	
	<div class="row-fluid table-bordered-header">
                <div class="col-md-1">&nbsp;</div>
		<div class="col-md-8"><b><?php echo $lang->translate('Article'); ?></b></div>
		<div class="col-md-1 last"><b><?php echo $lang->translate('Order'); ?></b></div>

	</div>
	
	<div id="article_sortable">		
		<?php foreach ($this->articles as $k => $entry): ?>
		<div class="row-fluid table-bordered-content <?php if(($k+1)%2): echo "odd"; endif;?>" id="<?php echo $entry->temp.'_'.$entry->id; ?>">				
                    <div class="col-md-1"><?php echo $k+1; ?></div>	
                    <div class="col-md-8">
				<div class="row-fluid no-border">	
					<?php if($entry->image):?>				
					<div class="col-md-3 no-border">
						<?php echo GlobalFunctions::getContentPreviewForList($entry->image);?> 
					</div>
					<?php endif; ?>
					<div class="pointer <?php if($entry->image):?> col-md-8 <?php else: ?> col-md-11 <?php endif; ?> no-border" id="tree_<?php echo $entry->id; ?>" section_parent="<?php echo $this->info['id']; ?>" article="<?php echo $entry->article; ?>" editable_section="<?php echo $entry->editable_section; ?>" temp="<?php echo $entry->temp; ?>">
						<div class="row-fluid no-border article_title">
							<b> <?php echo $this->escape($entry->title); ?> </b>								
						</div>
<!--						<div class="row-fluid no-border article_synopsis">								
							<?php //echo $entry->synopsis; ?>
						</div>-->
					</div>
				</div>				
			</div>
			<div class="col-md-1 last handler move"><i class="glyphicon glyphicon-move"></i></div>
			
		</div>					
		<?php endforeach; ?>
	</div>
	
		
</form>
</div>
<?php endif; ?>
 <script>
 $(document).ready(function(){
     $("#article_sortable").sortable(
		{
			handle: ".handler",
			axis: "y",
			cursor: "move",
                       
		}
	);	
	$("#article_sortable").disableSelection();
        
        //saves ordered articles
	$('#save_article_order').bind('click', function() {
             var section_list = $("#article_sortable").sortable("toArray");
             $('#section_order').val(section_list.join(','));
		$.ajax({
            type: "POST",
            url: '/core/article_article/saveorder',
            data: $("#frmArticlesOrder" ).serialize(),
            timeout : 20000,
            success: function(data) {
                     //alert(data);
                     var objData = jQuery.parseJSON(data);
                      //alert(objData.opcion);
                      if(objData.opcion=='highlight'){
                           parent.$("#order_highlight_value").val(objData.orden);
                      }else if(objData.opcion=='feature'){
                           parent.$("#order_feature_value").val(objData.orden);
                      }else{
                           parent.$("#order_homepage_value").val(objData.orden);
                      }
                     
                
                $.fancybox.close();
             
            }
       });
		
	});
 });
 </script>
