<?php $lang = Zend_Registry::get('Zend_Translate');
$front_ids = New Zend_Session_Namespace('ids');?>	
							
	<div id="section_login_container" class="col-md-4 col-md-offset-4">
            <form id="form_login_template" name="form_login_template" action="">
                <div class="form-group">
                    <label class="required" for="public_user_template"><?php echo '* '.$lang->translate("User"); ?></label>
                    <input type="text" class="form-control" id="public_user_template" name="public_user_template" />
                </div>
                <div class="form-group">
                    <label class="required" for="public_password_template"><?php echo '* '.$lang->translate("Password"); ?></label>
                    <input type="password" class="form-control" id="public_password_template" name="public_password_template" />
                </div>
			<label  id="error_login_template" name="error_login_template" class="error_validation hide"><?php echo $lang->translate("The username or password are wrong"); ?></label>
			<label  id="error_login_inactive_template" name="error_login_inactive_template" class="error_validation hide"><?php echo $lang->translate("This user is inactive"); ?></label>		
                        <input type="button" class="btn btn-primary" id="btnLogin_template" area="template" name="btnLogin_template" value="<?php echo $lang->translate("Login"); ?>"/><br/>
			<a class="pointer" href="#form_register_template" area="template" id="register_template"><?php echo $lang->translate("Register"); ?></a><br/>
			<a class="pointer" href="#form_forgot_template" area="template" id="forgot_template"><?php echo $lang->translate("Forgot your password?"); ?></a>	
		</form>			
	</div>
	
        <div class="hide">
            <form class="form-login margin-fancy " id="form_register_template" name="form_register_template" action="">
                <h3 class="text-center"><?php echo '* '.$lang->translate("Register Form"); ?></h3>

                    <div class="form-group col-md-6">
                        <label for="public_user_name_template"><?php echo '* '.$lang->translate("Name"); ?></label>
                        <input type="text" class="form-control" id="public_user_name_template" name="public_user_name_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_last_name_template"><?php echo '* '.$lang->translate("Lastname"); ?></label>
                        <input type="text" class="form-control" id="public_user_last_name_template" name="public_user_last_name_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_identification_template"><?php echo '* '.$lang->translate("Identification"); ?></label>
                        <input type="text" class="form-control" id="public_user_identification_template" name="public_user_identification_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_email_template"><?php echo '* '.$lang->translate("Email"); ?></label>
                        <input type="text" class="form-control email" id="public_user_email_template" name="public_user_email_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_phone_template"><?php echo '* '.$lang->translate("Phone"); ?></label>
                        <input type="text" class="form-control" id="public_user_phone_template" name="public_user_phone_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_username_template"><?php echo '* '.$lang->translate("Username"); ?></label>
                        <input type="text" class="form-control" id="public_user_username_template" name="public_user_username_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_password_template"><?php echo '* '.$lang->translate("Password"); ?></label>
                        <input type="password" class="form-control" id="public_user_password_template" name="public_user_password_template" />
                    </div>
                    <div class="form-group col-md-6">
                        <label for="public_user_cpassword_template"><?php echo '* '.$lang->translate("Confirm Password"); ?></label>
                        <input type="password" class="form-control" id="public_user_cpassword_template" name="public_user_cpassword_template" />
                    </div>

                <div class="text-center col-md-12">
                        <input class="btn btn-primary" type="button" id="btn_register_user_template" name="btn_register_user_template" value="<?php echo $lang->translate("Send"); ?>" />
                        <input type="hidden" id="website_id" name="website_id" value="<?php echo $front_ids->website_id; ?>" />
                        <input type="hidden" id="area" name="area" value="template" />
                        <input type="hidden" id="error_email_template" name="error_email_template" value="<?php echo $lang->translate("The email address already has been registered"); ?>" />
                        <input type="hidden" id="error_username_template" name="error_username_template" value="<?php echo $lang->translate("The username already has been registered"); ?>" />
                </div>																																				
            </form>
        </div>
	
        <div class="hide">
            <form class="span8 form-login margin-fancy" id="form_forgot_template" name="form_forgot_template" action="">
                <div class="text-center">
                    <h3><?php echo $lang->translate("Password Reset"); ?></h3>
                </div><br/>


                <div class="form-group">
                    <label for="public_for_user_email_template"><?php echo $lang->translate("Email"); ?></label>
                    <input type="text" class="form-control" id="public_for_user_email_template" name="public_for_user_email_template" />
                </div>

                <div class="form-group text-center">
                    <input class="btn btn-primary" type="button" id="btn_send_password_user_template" name="btn_send_password_user_template" value="<?php echo $lang->translate("Send"); ?>" />
                </div>										
            </form>
        </div>							