<?php 
$lang = Zend_Registry::get ( 'Zend_Translate' );
?>				
    <form class="span12 form-horizontal margin-fancy" id="form_register_'.$area_id.'" name="form_register_'.$area_id.'" action="">
            <div class="row-fluid center">
                    <h3> <?php echo $lang->translate('User'); ?></h3>
            </div><br/>
            <div class="row-fluid">
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Nombre'); ?></label>
                                    <div class="controls">
                                            <input type="text" id="public_user_name_'.$area_id.'" name="public_user_name_'.$area_id.'" />
                                    </div>
                            </div>
            </div>
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Lastname'); ?></label>
                                    <div class="controls">
                                            <input type="text" id="public_user_last_name_'.$area_id.'" name="public_user_last_name_'.$area_id.'" />
                                    </div>
                            </div>
            </div>								      												
            </div>
            <div class="row-fluid">
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Identificattion'); ?></label>
                                    <div class="controls">
                                            <input type="text" id="public_user_identification_'.$area_id.'" name="public_user_identification_'.$area_id.'" />
                                    </div>
                            </div>
            </div>
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Email'); ?></label>
                                    <div class="controls">
                                            <input type="text" id="public_user_email_'.$area_id.'" name="public_user_email_'.$area_id.'" />
                                    </div>
                            </div>
            </div>								      												
            </div>		
            <div class="row-fluid">
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label"> <?php echo $lang->translate('Phone'); ?></label>
                                    <div class="controls">
                                            <input type="text" id="public_user_phone_'.$area_id.'" name="public_user_phone_'.$area_id.'" />
                                    </div>
                            </div>
            </div>
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Username'); ?></label>
                                    <div class="controls">
                                            <input type="text" id="public_user_username_'.$area_id.'" name="public_user_username_'.$area_id.'" />
                                    </div>
                            </div>
            </div>								      												
            </div>	
            <div class="row-fluid">
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Password'); ?></label>
                                    <div class="controls">
                                            <input type="password" id="public_user_password_'.$area_id.'" name="public_user_password_'.$area_id.'" />
                                    </div>
                            </div>
            </div>	
            <div class="span6">				      							      		
                    <div class="control-group">
                                    <label class="control-label">* <?php echo $lang->translate('Confirm Password'); ?></label>
                                    <div class="controls">
                                            <input type="password" id="public_user_cpassword_'.$area_id.'" name="public_user_cpassword_'.$area_id.'" />
                                    </div>
                            </div>
            </div>								      								      												
            </div>
            <div class="row-fluid center">
                    <input class="btn " type="button" id="btn_register_user_'.$area_id.'" name="btn_register_user_'.$area_id.'" value=" <?php echo $lang->translate('Enviar'); ?>" />
                    <input type="hidden" id="website_id" name="website_id" value="'.$front_ids->website_id.'" />
                    <input type="hidden" id="area" name="area" value="'.$area_id.'" />
                    <input type="hidden" id="error_email_'.$area_id.'" name="error_email_'.$area_id.'" value="'. $lang->translate('The email address already has been registered').'" />
                    <input type="hidden" id="error_username_'.$area_id.'" name="error_username_'.$area_id.'" value="'. $lang->translate('The username already has been registered').'" />
            </div>																																				
    </form>