<?php $content_field = new Core_Model_ContentField();?>
<?php $count_contents = 0; ?>
<?php if(!$this->private || ($this->private && isset($_SESSION['external_user']))): ?>	
<div class="carrusel" id="section-<?php echo $this->contents[0]['section_id'];?>">
<?php $ite = 0; ?>
<div class="cycle-template">
    <div class="cycle-prev" id="prev-<?php echo $this->contents[0]['section_id'];?>"></div>
    <div class="cycle-next" id="next-<?php echo $this->contents[0]['section_id'];?>"></div>
    <div class="cycle-pager"></div>
<?php foreach($this->contents as $key => $value): ?>
    <article>
    <?php echo $this->previewHelper($value['section_id'], $value['content_id']); ?>
        	
        <?php $count_contents++;?>
    </article>
<?php endforeach; ?>
    
    </div>
<?php endif; ?>
    
</div>
<script type="text/javascript">
$('.cycle-template').cycle({
    speed: 1000,
    timeout: 4000,
    fx: "fade",
    swipe:true,
    slides : "> article"
});
</script>