<?php
foreach($this->section_floors as $key => $subsection){
    $this->col_number = $subsection['col_number'];
    $this->section_title = $subsection['section_title'];
    $this->section_subtitle = $subsection['section_subtitle'];
    $this->title = $subsection['title'];
    $this->subtitle = $subsection['subtitle'];
    $this->synopsis = $subsection['synopsis'];
    $this->publish_date = $subsection['publish_date'];
    $this->expire_date = $subsection['expire_date'];
    $this->section_id = $subsection['id'];
    $this->contents = $subsection['contents'];
    $this->section_images = $subsection['section_images'];
    $this->articles = $subsection['articles'];
    //session storage vals
    $session_render_vals = new Zend_Session_Namespace('render_vals_front');
    $session_render_vals->area_width = 'col-md-12';
    $session_render_vals->section_cols = $subsection['col_number'];
    
    include($subsection['section_filename_tpl']);
}
?>
