<div id="header">
	<div class="container">
            <div class="col-md-12" id="header_logo"></div>
            <div class="col-md-12">
                <div id="header_name" class="center"></div>
            </div>
	</div>
</div>

<div class="container">
    <div class="navbar">
        <div class="navbar-inner">
            <div id="menu" class="container"></div>
        </div>
    </div>										
</div>

<div class="container" id="wica_main_area">
    <div id="wica_area_content"></div>
</div>

<div class="container" id="footer"></div>
