<div class="row-fluid" id='header'>
	<div class="span12">
		<div class="row-fluid"> &nbsp; </div>
		<div class="row-fluid">
			<div class="span3" id="header_logo"></div>
			<div class="row-fluid">
				<div id="header_name" class="title center"></div>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container" id="menu"></div>
			</div>
		</div>
	</div>		  		  		
</div>

<div class="row-fluid" id="wica_main_area">
  	<div class="span3">
  		<div class="row-fluid" id="wica_area_2"></div>
  		<div id="wica_area_3" class="row-fluid"></div>
  	</div>
  	<div class="span9">
  		<div class="row-fluid" id="wica_area_content"></div>
  	</div>
</div>

<div class="row-fluid" id="footer"></div>
