<div id='header'>
    <div class="row">&nbsp;</div>
	<div class="container">
            <div class="span3 col-md-3" id="header_logo"></div>
            <div class="span9 col-md-9">
                <div id="header_name" class="title center"></div>
            </div>
	</div>
</div>

<div class="container">
	<div class="span12 col-md-12">
		<div class="page-header">
			<div class="navbar">
				<div class="navbar-inner">
					<div id="menu" class="container"></div>
				</div>
			</div>										
		</div>
	</div>		  		  		
</div>

<div class="container" id="wica_main_area">
	<div class="span12 col-md-12">
  		<div id="wica_area_content"></div>
  	</div>
</div>

<div class="row-fluid row" id="footer"></div>
