<!-- 
 *	View that contains a product form to create a new element
 *
 * @category   WicaWeb
 * @package    Products_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->

<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<script type="text/javascript" charset="utf-8">
	var max_size = "<?php echo $lang->translate('Maximum size');?>";
	var supported_extension = "<?php echo $lang->translate('Supported files');?>";
	var productdescription_remote_message = "<?php echo $lang->translate('Product name already exist');?>";
</script>

<?php $available_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$available); ?>
<?php $feature_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$feature); ?>
<?php $status_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$status); ?>
     	   
<div class="row-fluid line">
	<div class="span12">
		<div class="page-header-wica center">
			<h1><?php echo $lang->translate('Edit Product'); ?></h1>		
		</div>
	</div>	
</div>

<div class="row-fluid line">
	<div class="span12"></div>	
</div>

<form class="well <?php echo $this->form->getAttrib('class'); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" method="<?php echo $this->form->getMethod(); ?>" enctype="multipart/form-data">
<div class="row-fluid">
	<div class="span6">
		<div class="row-fluid">							
			<?php echo $this->form->id->renderViewHelper(); ?>
			<?php echo $this->form->section_id->renderViewHelper(); ?>
	      	<div class="control-group">
				<label class="control-label"><?php echo $this->form->name->getLabel(); ?></label>
				<div class="controls">
					<?php echo $this->form->name->renderViewHelper(); ?>										
				</div>
			</div>
		</div>
	</div>
	<div class="span5">				      							      		
      	<div class="control-group">
			<label class="control-label"><?php echo $this->form->description->getLabel(); ?></label>
			<div class="controls">
				<?php echo $this->form->description->renderViewHelper(); ?>
			</div>
		</div>
    </div>	
</div>

<div class="row-fluid">
	<div class="span6">												
		<div class="control-group">
			<label class="control-label"><?php echo $lang->translate('Image').':' ?></label>
			<div class="controls">
				<input type="text" disabled="disabled" id="product_fileLabel">
				<?php echo $this->form->product_img->renderViewHelper(); ?>
				<input type="hidden" name="product_hdnNameFile" id="product_hdnNameFile" value=""/>
			</div>
		</div>		
		<div class="control-group">
			<label class="control-label"><?php echo $this->form->product_imageprw->getLabel(); ?></label>
			<div class="controls">
				<?php echo $this->form->product_imageprw->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
			</div>
		</div>		
		<?php echo $this->form->product_file_img->renderViewHelper(); ?>
		<?php //echo $this->form->product_id_img->renderViewHelper(); ?>
	</div>
	<div class="span6">	
		<div class="control-group">
			<label class="control-label"><?php echo '* '.$lang->translate('Available').':'; ?></label>
			<div class="controls">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_available_arr = array_keys($available_opt);
						$default_available_opt = $default_available_arr[1]; ?>							
					<?php foreach($available_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_available_opt == $k): echo 'active'; endif; ?>" id="available-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->available->renderViewHelper(); ?>
			</div>
		</div>
	</div>	
</div>

<div class="row-fluid">
	<div class="span6">	
		<div class="control-group">
			<label class="control-label"><?php echo '* '.$lang->translate('Status').':'; ?></label>
			<div class="controls">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_status_arr = array_keys($status_opt);
						$default_status_opt = $default_status_arr[0]; ?>							
					<?php foreach($status_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_status_opt == $k): echo 'active'; endif; ?>" id="status-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->status->renderViewHelper(); ?>
			</div>
		</div>
	</div>
	<div class="span6">
		<div class="control-group">
			<label class="control-label"><?php echo '* '.$lang->translate('Feature').':'; ?></label>
			<div class="controls">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_feature_arr = array_keys($feature_opt);
						$default_feature_opt = $default_feature_arr[1]; ?>							
					<?php foreach($feature_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_feature_opt == $k): echo 'active'; endif; ?>" id="feature-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->feature->renderViewHelper(); ?>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid line">
	<div class="span12"></div>	
</div>

<div class="row-fluid">
	<div class="span6">	
		<div class="control-group">
			<label class="control-label"><?php echo $lang->translate('Products catalog').':'; ?></label>
			<div class="controls">
				<?php echo $this->form->add_feature->renderViewHelper(); ?>
				<a id="anchor_add_product" class="hide" href="#products_container"></a>		
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<table id="tmp_products" name="tmp_products" class="table table-bordered hide">
		<thead>
			<th><?php echo $lang->translate('Code'); ?></th>
			<th><?php echo $lang->translate('Description'); ?></th>
			<th><?php echo $lang->translate('Price'); ?></th>
			<th><?php echo $lang->translate('Weight'); ?></th>
			<th><?php echo $lang->translate('Tools'); ?></th>
		</thead>
		<tbody>
			 <?php if(count($this->products)>0): ?>
				<?php foreach ($this->products as $mkey => $product): ?>                       
					<tr id="tmp_product_<?php echo $mkey+1; ?>">
						<td id="tmp_product_code_<?php echo $mkey+1; ?>" name="tmp_product_code_<?php echo $mkey+1; ?>"><?php echo $product->code; ?></td>
						<td id="tmp_product_description_<?php echo $mkey+1; ?>" name="tmp_product_description_<?php echo $mkey+1; ?>"><?php echo $product->description; ?></td>
						<td id="tmp_product_price_<?php echo $mkey+1; ?>" name="tmp_product_price_<?php echo $mkey+1; ?>"><?php echo $product->price; ?></td>						
						<td id="tmp_product_weight_<?php echo $mkey+1; ?>" name="tmp_product_weight_<?php echo $mkey+1; ?>"><?php echo $product->weight; ?></td>
						<td id="actions_tmp_product_<?php echo $mkey+1; ?>" name="actions_tmp_product_<?php echo $mkey+1; ?>"><i id="edit_element_<?php echo $mkey+1; ?>" element="<?php echo $mkey+1; ?>" class="pointer icon-pencil" title="Edit"></i>|<i id="remove_element_<?php echo $mkey+1; ?>" element="<?php echo $mkey+1; ?>" class="pointer icon-trash" title="Delete"></i></td>
					</tr>                        
				<?php endforeach; ?>  
			<?php endif;?>    
		</tbody>            
	</table>
</div>

<div id="hdn_products" name="hdn_products">
	<?php if (count($this->products)>0): ?>
        <?php foreach ($this->products as $mkey => $product): ?>                                   
            <div id="hdn_product_<?php echo $mkey+1; ?>">
                <input type="hidden" id="hdn_product_code_<?php echo $mkey+1; ?>" name="hdn_product_code_[<?php echo $mkey+1; ?>]" value="<?php echo $product->code; ?>" />
				<input type="hidden" id="hdn_product_description_<?php echo $mkey+1; ?>" name="hdn_product_description_[<?php echo $mkey+1; ?>]" value="<?php echo $product->description; ?>" />
				<input type="hidden" id="hdn_product_price_<?php echo $mkey+1; ?>" name="hdn_product_price_[<?php echo $mkey+1; ?>]" value="<?php echo $product->price; ?>" />
				<input type="hidden" id="hdn_product_price_sale_<?php echo $mkey+1; ?>" name="hdn_product_price_sale_[<?php echo $mkey+1; ?>]" value="<?php echo $product->price_sale; ?>" />
				<input type="hidden" id="hdn_product_weight_<?php echo $mkey+1; ?>" name="hdn_product_weight_[<?php echo $mkey+1; ?>]" value="<?php echo $product->weight; ?>" />
				<input type="hidden" id="hdn_product_Filelabel_<?php echo $mkey+1; ?>" name="hdn_product_Filelabel_[<?php echo $mkey+1; ?>]" value="<?php echo $product->image; ?>" />
				<input type="hidden" id="hdn_product_hdnNameFile_<?php echo $mkey+1; ?>" name="hdn_product_hdnNameFile_[<?php echo $mkey+1; ?>]" value="" />
				<input type="hidden" id="hdn_product_file_img_<?php echo $mkey+1; ?>" name="hdn_product_file_img_[<?php echo $mkey+1; ?>]" value="<?php echo $product->image ?>" />
				<input type="hidden" id="hdn_product_id_<?php echo $mkey+1; ?>" name="hdn_product_id_[<?php echo $mkey+1; ?>]" value="<?php echo $product->id ?>"/>
                
            </div>                        
        <?php endforeach; ?>  
    <?php endif; ?>   
</div>

</form>

<div class="hide">	
	<div id="products_container" name="products_container"></div>
</div>

<div class="row-fluid">
	<div class="center well">
		<div class="row-fluid">					
			<?php echo $this->form->submit_button->renderViewHelper(); ?>
			&nbsp;&nbsp;
			<?php echo $this->form->cancel_button->renderViewHelper(); ?>		
		</div>
	</div>
</div>
