<?php 
/**
 * Products list
 *
 * @category   WicaWeb
 * @package    Products_View
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   David Rosales
 * @version    1.0
 *
 */	
?>

<?php $lang = Zend_Registry::get('Zend_Translate');?>

<?php if($this->section_id!='all'): ?>
<div class="container-fluid option_bar_container line">
	<?php foreach($this->cms_links as $action_id => $opt): ?>
	<?php if($opt['action']=='new'): ?>	
	<ul class="nav nav-pills pull-right">
        <li>
            <a  id="new_product" class="pointer"><?php echo $lang->translate('New Product'); ?></a>
        </li>
    </ul>
    <?php endif; ?>    
    <?php endforeach; ?>
</div>
<?php endif; ?>    

<div class="container-fluid line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<?php if ($this->products_list && count($this->products_list)>0): ?>

<div class="row-fluid">
	<div class="alert alert-info general_legend_text">
		<div class="legend_inner_left">
			<i class="glyphicon glyphicon-info-sign"></i>
		</div>
		<div class="right">
			<i class="glyphicon glyphicon-pencil"></i> <?php echo $lang->translate('Update'); ?> &nbsp;&nbsp;
			<i class="glyphicon glyphicon-trash"></i> <?php echo $lang->translate('Delete'); ?> &nbsp;&nbsp;
			<i class="glyphicon glyphicon-move"></i> <?php echo $lang->translate('Order'); ?> 
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Products list'); ?></h1>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	var delete_question = "<?php echo $lang->translate('This product will be deleted. Would you like to continue?');?>";
</script>
	
<form action="" method="post" name="frmProductsOrder" id="frmProductsOrder">
	
	<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">
	
	<div class="row-fluid table-bordered-header">	
		<div class="col-md-6"><b><?php echo $lang->translate('Product name'); ?></b></div>		
		<div class="col-md-1"><b><?php echo $lang->translate('Order'); ?></b></div>
		<?php if($this->section_id!='all'): ?>
		<div class="col-md-4 last"><b><?php echo $lang->translate('Tools'); ?></b></div>
		<?php endif; ?>
	</div>
	
	<div id="sortable">
		<?php foreach ($this->products_list as $k => $entry): ?> 
		<div class="row-fluid table-bordered-content <?php if(($k+1)%2): echo "odd"; endif;?>" id="<?php echo $entry['id']; ?>">	
			<div class="col-md-6 pointer"><a class="pointer" id="edit_product_<?php echo $entry['id'];?>" product_id="<?php echo $entry['id'];?>"> <?php echo $entry['name']; ?> </a></div>
			<div class="col-md-1 handler move"><i class="glyphicon glyphicon-move"></i></div>
			<?php if($this->section_id!='all'): ?>
				<div class="col-md-4 last pointer">
				<?php foreach($this->cms_links as $action_id => $opt): ?>
				<?php if($opt['action']=='edit'): ?>
				<a class="pointer" id="edit_product_<?php echo $entry['id']?>" product_id="<?php echo $entry['id'];?>" title="<?php echo $lang->translate('Update'); ?>"><i class="glyphicon glyphicon-pencil"></i></a> /
				<?php endif; ?>
				<?php if($opt['action']=='delete'): ?>
				<a class="pointer" id="delete_product_<?php echo $entry['id']?>" product_id="<?php echo $entry['id'];?>" title="<?php echo $lang->translate('Delete'); ?>"><i class="glyphicon glyphicon-trash"></i></a>
				<?php endif; ?>
				<?php endforeach; ?>	
				</div>		
			<?php endif; ?>
		</div>					
		<?php endforeach ?>
	</div>
	<?php if($this->total_sec == $this->assigned_sec): ?>
	<div class="row-fluid">
		<input type="hidden" id="product_order" name="product_order" value="">
		<input type="hidden" id="identifier" name="identifier" value="products" />
		<br>  
		<input type="button" id="save_order" name="save_order" class="btn btn-success" value="<?php echo $lang->translate('Save order'); ?>">
	</div>
	<?php endif; ?>
</form>	
<?php else: ?>	
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No products found'); ?></h3>
		<input type="hidden" id="section_id" name="section_id" value="<?php echo $this->section_id;?>">
	</div>	
<?php endif ?>

