<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<div class="row-fluid">
	<div class="col-md-1">&nbsp;</div>
	<div class="col-md-10">
		<div class="row-fluid center">
			<div class="page-header">
				<h3><?php echo $lang->translate('Product feature'); ?></h3>
			</div>
		</div>
		<form id="product_form" name="product_form" class="form-horizontal">
			<div class="row-fluid">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"> <?php echo '* '.$lang->translate('Code').':'; ?> </label>
						<div class="col-sm-8">
							<input type="text" id="product_code" name="product_code" class="form-control">	
							<label id="repeated_product_code" class="hide error" for="code" generated="true"><?php echo $lang->translate('Product code already exists'); ?></label>						
						</div>
					</div>
				</div>		
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"> <?php echo $lang->translate('Description').':'; ?> </label>
						<div class="col-sm-8">
							<input type="text" id="product_description" name="product_description" class="form-control">														
						</div>
					</div>
				</div>
			</div>
			<div class="row-fluid">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"> <?php echo '* '.$lang->translate('Price').':'; ?> </label>
						<div class="col-sm-8">
							<input type="text" id="product_price" name="product_price" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"> <?php echo $lang->translate('Sale price').':'; ?> </label>
						<div class="col-sm-8">
							<input type="text" id="product_price_sale" name="product_price_sale" class="form-control">					
						</div>
					</div>
				</div>
			</div>
			<div class="row-fluid">
				<div class="col-md-6">
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"> <?php echo $lang->translate('Weight').':'; ?> </label>
						<div class="col-sm-8">						
							<input type="text" id="product_weight" name="product_weight" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-md-6">												
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"><?php echo $lang->translate('Image').':' ?></label>
						<div class="col-sm-8">
							<input type="text" disabled="disabled" id="catalog_fileLabel">
							<button id="catalog_img" class="btn btn-default" type="button" name="catalog_img"><?php echo $lang->translate('Search') ?></button>
							<input type="hidden" name="catalog_hdnNameFile" id="catalog_hdnNameFile" value=""/>
						</div>
					</div>		
					<div class="form-group">
						<label class="col-sm-4 control-label form_label"></label>
						<div class="col-sm-8">
							<input id="catalog_imageprw" class="preview_img hide" type="image" onclick="return false;" alt="" src="" name="catalog_imageprw">
						</div>
					</div>					
					<input id="catalog_file_img" type="hidden" value="" name="catalog_file_img">
					<input id="catalog_id" type="hidden" value="" name="catalog_id">
				</div>				
			</div>
			<div class="row-fluid">
				<div class="col-md-12" >
					<div class="form-actions center">
						<input type="button" id="btnAddproduct" name="btnAddproduct" class="hide btn btn-primary" value="<?php echo $lang->translate('Add'); ?>">
						<input type="button" id="btnEditproduct" name="btnEditproduct" class="hide btn btn-primary" value="<?php echo $lang->translate('Edit'); ?>">
					</div>
				</div>	
			</div> 
		</form>
	</div>
	<div class="col-md-1">&nbsp;</div>
</div>
