<!-- 
 *	View that contains a product form to create a new element
 *
 * @category   WicaWeb
 * @package    Products_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->

<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<script type="text/javascript" charset="utf-8">
	var max_size = "<?php echo $lang->translate('Maximum size');?>";
	var supported_extension = "<?php echo $lang->translate('Supported files');?>";
	var productdescription_remote_message = "<?php echo $lang->translate('Product name already exist');?>";
        var delete_feature = "<?php echo $lang->translate('This feature will be deleted. Would you like to continue?');?>";
</script>

<?php $available_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$available); ?>
<?php $feature_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$feature); ?>
<?php $highlight_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$highlight); ?>
<?php $status_opt = GlobalFunctions::arrayTranslate(Products_Model_Products::$status); ?>
     	   
<div class="row-fluid center">
    <div class="page-header-wica center">
        <h1><?php echo $lang->translate('New Product'); ?></h1>				
    </div>	
</div>
<form class="<?php echo $this->form->getAttrib('class'); ?>" id="<?php echo $this->form->getAttrib('id'); ?>" method="<?php echo $this->form->getMethod(); ?>" enctype="multipart/form-data">
<div class="row-fluid">
	<div class="col-md-8">
		
			<?php echo $this->form->id->renderViewHelper(); ?>
			<?php echo $this->form->section_id->renderViewHelper(); ?>
                        <?php echo $this->form->website_id->renderViewHelper(); ?>
	      	<div class="form-group">
				<label class="col-sm-4 control-label form_label"><?php echo $this->form->name->getLabel(); ?></label>
				<div class="col-sm-8">
					<?php echo $this->form->name->renderViewHelper(); ?>										
				</div>
                </div>
		
	</div>
</div>
<div class="row-fluid">
	<div class="col-md-8">				      							      		
      	<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo $this->form->description->getLabel(); ?></label>
			<div class="col-sm-8">
				<?php echo $this->form->description->renderViewHelper(); ?>
			</div>
		</div>
    </div>	
</div>

<div class="row-fluid">
	<div class="col-md-6">												
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo $lang->translate('Image').':' ?></label>
			<div class="col-sm-8">
				<input type="text" disabled="disabled" id="product_fileLabel">
				<?php echo $this->form->product_img->renderViewHelper(); ?>
				<input type="hidden" name="product_hdnNameFile" id="product_hdnNameFile" value=""/>
			</div>
		</div>		
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo $this->form->product_imageprw->getLabel(); ?></label>
			<div class="col-sm-8">
				<?php echo $this->form->product_imageprw->removeDecorator('HtmlTag')->removeDecorator('Label'); ?>
			</div>
		</div>		
		<?php echo $this->form->product_file_img->renderViewHelper(); ?>
	</div>
        <div class="col-md-6">												
		<div class="form-group">
			<label class="col-sm-4 control-label form_label">Ficha:</label>
			<div class="col-sm-8">
				<input type="text" disabled="disabled" id="product_fichaLabel">
				<?php echo $this->form->product_ficha->renderViewHelper(); ?>
				<input type="hidden" name="product_hdnNameFicha" id="product_hdnNameFicha" value=""/>
			</div>
		</div>			
		<?php echo $this->form->product_file_ficha->renderViewHelper(); ?>
	</div>
</div>
    <div class="row-fluid">
	<div class="col-md-6">	
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Available').':'; ?></label>
			<div class="col-sm-8">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_available_arr = array_keys($available_opt);
						$default_available_opt = $default_available_arr[0]; ?>							
					<?php foreach($available_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_available_opt == $k): echo 'active'; endif; ?>" id="available-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->available->renderViewHelper(); ?>
			</div>
		</div>
	</div>	
        <div class="col-md-6">
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Feature').':'; ?></label>
			<div class="col-sm-8">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_feature_arr = array_keys($feature_opt);
						$default_feature_opt = $default_feature_arr[1]; ?>							
					<?php foreach($feature_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_feature_opt == $k): echo 'active'; endif; ?>" id="feature-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->feature->renderViewHelper(); ?>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
        <div class="col-md-6">
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Highlight').':'; ?></label>
			<div class="col-sm-8">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_highlight_arr = array_keys($highlight_opt);
						$default_highlight_opt = $default_highlight_arr[1]; ?>							
					<?php foreach($highlight_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_highlight_opt == $k): echo 'active'; endif; ?>" id="highlight-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->highlight->renderViewHelper(); ?>
			</div>
		</div>
	</div>
	<div class="col-md-6">	
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Status').':'; ?></label>
			<div class="col-sm-8">
				<div class="btn-group" data-toggle="buttons-radio">
					<?php $default_status_arr = array_keys($status_opt);
						$default_status_opt = $default_status_arr[0]; ?>							
					<?php foreach($status_opt as $k => $opt): ?>
					<input type="button" class="btn btn-primary <?php if($default_status_opt == $k): echo 'active'; endif; ?>" id="status-<?php echo $k; ?>" value="<?php echo $opt; ?>">
					<?php endforeach; ?>
				</div>
				<?php echo $this->form->status->renderViewHelper(); ?>
			</div>
		</div>
	</div>
	
</div>

<div class="row-fluid line">
	<div class="col-md-12"></div>	
</div>

<div class="row-fluid">
	<div class="col-md-6">	
		<div class="form-group">
			<label class="col-sm-4 control-label form_label"><?php echo $lang->translate('Products catalog').':'; ?></label>
			<div class="col-sm-8">
				<?php echo $this->form->add_feature->renderViewHelper(); ?>
				<a id="anchor_add_product" class="hide" href="#products_container"></a>		
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<table id="tmp_products" name="tmp_products" class="table table-bordered hide">
		<thead>
			<th><?php echo $lang->translate('Code'); ?></th>
			<th><?php echo $lang->translate('Description'); ?></th>
			<th><?php echo $lang->translate('Price'); ?></th>
			<th><?php echo $lang->translate('Weight'); ?></th>
			<th><?php echo $lang->translate('Tools'); ?></th>
		</thead>
		<tbody>
			  
		</tbody>            
	</table>
</div>

<div id="hdn_products" name="hdn_products">
   
</div>

</form>

<div class="hide">	
	<div id="products_container" name="products_container"></div>
</div>

<div class="row-fluid">
	<div class="center well">
		<div class="row-fluid">					
			<?php echo $this->form->submit_button->renderViewHelper(); ?>
			&nbsp;&nbsp;
			<?php echo $this->form->cancel_button->renderViewHelper(); ?>		
		</div>
	</div>
</div>
