<?php
//translate library
$lang = Zend_Registry::get ( 'Zend_Translate' ); ?>

<div class="row-fluid center">
	<h2><?php echo $lang->translate("Catalog"); ?></h2>
</div>

<div class="row-fluid">	
	<table class="table table-bordered">
	  <thead>
	  <tr>
	    <th><?php echo $lang->translate("Image"); ?></th>
	    <th><?php echo $lang->translate("Description"); ?></th>
	    <th><?php echo $lang->translate("Price"); ?></th>
	    <th><?php echo $lang->translate("Price Sale"); ?></th>
	    <th><?php echo $lang->translate("Weight"); ?></th>
	  </tr>
	  </thead>
	  <tbody>
<?php foreach($this->catalog as $cat){ ?>	  
	  <tr>
	    <td>
			<?php 
			$product = '<a  href="/uploads/products/' . $cat->image . '" class="highslide">';
			$product .= '<img class="preview_list_img thumbnail"';
			$product.= ' style="border: thin solid; color: black !important;"';
			$product .= ' src="'. $cat->image .'"/>';
			$product .= '</a>';
			echo $product;
			?>	    
	    
	    </td>
	    <td><?php echo $cat->description; ?></td>
	    <td><?php echo $cat->price; ?></td>
	    <td><?php echo $cat->price_sale; ?></td>
	    <td><?php echo $cat->weight; ?></td>
	  </tr>
<?php } ?>	
		</tbody>  
	</table>
	
</div>	