<?php
//translate library
$lang = Zend_Registry::get ( 'Zend_Translate' ); ?>


<?php print_r(json_encode($this->catalog));?>

<div class="span4">
	<img id="big_catalog_img" class="row-fluid preview_list_img thumbnail" src="<?php echo '/uploads/products/'.$this->product->image; ?> ">
</div>
<div class="span">
  <ul id="mycarousel" class="jcarousel jcarousel-skin-tango">
  	<?php foreach($this->catalog as $cat){ ?>
  		<?php if($cat->image):?>
	    <li class="pointer" ><img id="catalog_<?php echo $cat->id;?>" class="preview_list_img thumbnail" src="<?php echo '/uploads/products/'.$cat->image; ?>" width="75" height="75" alt="" description="<?php echo $cat->description; ?>" price="<?php echo $lang->translate('Price').': '.$cat->price_sale;?>" /></li>
	    <?php else: ?>
	    <li class="pointer"><img id="catalog_<?php echo $cat->id;?>" class="preview_list_img thumbnail" src="<?php echo '/images/no_image.jpg'; ?>" width="75" height="75" description="<?php echo $cat->description; ?>" alt="" price="<?php echo $lang->translate('Price').': '.$cat->price_sale;?>" /></li>
	    <?php endif;?>
	<?php } ?>    
  </ul>

</div>

<div class="span6">

<div class="row-fluid" id="tabs">
	<ul>
		<li><a href="#tabs-1"><?php echo $lang->translate("Description"); ?></a></li>
		<li><a href="#tabs-2"><?php echo $lang->translate("Comments"); ?></a></li>
		<li><a href="#tabs-3"><?php echo $lang->translate("Features"); ?></a></li>
	</ul>
	<div id="tabs-1" class="tabs_style">
		<p><?php echo $this->product->description; ?></p>
		<div id="price_section" class="right" style="font-size: medium;"></div>
	</div>
	<div id="tabs-2" class="tabs_style">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quam purus, interdum in consequat eu, consequat vel ante. Phasellus sed mi eu sem suscipit laoreet eu in felis. Phasellus est quam, tempor non malesuada non, imperdiet eu lorem. Integer vitae sem ligula. Integer risus sem, bibendum vel adipiscing sed, sagittis et nulla. Etiam facilisis elit quam. Donec tempus, metus a tempor viverra, eros libero varius augue, id pharetra mi lacus at lorem. Vestibulum tempor imperdiet neque, ac fermentum orci consequat eget. Pellentesque interdum massa et urna bibendum aliquam. Morbi facilisis ante et orci iaculis auctor. Phasellus id massa ante, ut laoreet diam.</p>
	</div>
	<div id="tabs-3" class="tabs_style">
		<p id="features_section"></p>
	</div>
</div>

</div>