<!-- 
 *	View that contains a list of available profiles
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<?php foreach($this->profile_links as $action_id => $opt): ?>
<?php if($opt['action']=='new'): ?>
<div class="row-fluid option_bar_container">
	<ul class="nav nav-pills pull-right">
        <li>
            <a href="/core/profile_profile/new"><?php echo $lang->translate('New profile'); ?></a>
        </li>
    </ul>
</div>
<?php endif; ?>
<?php endforeach; ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="row-fluid">
	<div class="page-header-wica center">
		<h1><?php echo $lang->translate('Profile list'); ?></h1>
	</div>
</div>

<?php if (count($this->profiles)>0): ?>
<div class="row-fluid">
	<table class="table table-bordered table-bordered-wica">
	  <tr>
	    <th><?php echo $lang->translate('Number'); ?></th>     
	    <th><?php echo $lang->translate('Name'); ?></th>  
	    <th><?php echo $lang->translate('Status'); ?></th>
	    <th><?php echo $lang->translate('Tools'); ?></th>
	  </tr>
	  <?php foreach ($this->profiles as $k => $profile): ?>
	  <tr class="<?php if(($k+1)%2): echo "odd"; endif;?>">
	    <td align="center"><?php echo ($k+1)?></td>        
	    <td><?php echo $profile->name; ?></td>    
	    <td><?php echo $this->status[$profile->status]; ?></td>
	    <td>
	    	<?php if ($profile->id != 1): ?>
	    	<?php foreach($this->profile_links as $action_id => $opt): ?>
				<?php if($opt['action']=='edit'): ?>
		    		<a href="/core/profile_profile/edit?<?php echo 'id='.$profile->id; ?>" title="<?php echo $lang->translate('Update'); ?>"><i class="icon-pencil"></i></a>
		    	<?php endif; ?>
			<?php endforeach; ?>
	    	<?php else:?>
				---	
			<?php endif;?>    	
	    </td> 
	  </tr>
	  <?php endforeach; ?>  
	</table>
</div>
<?php else:?>
	<div class="row-fluid center">
		<h3><?php echo $lang->translate('No profiles');?></h3>
	</div>	
<?php endif;?>

