<!-- 
 *	View that contain profile options
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<script type="text/javascript" charset="utf-8">
	var next_step = "<?php echo $lang->translate('Next step');?>";
	var back_step = "<?php echo $lang->translate('Back step');?>";
	var last_step = "<?php echo $lang->translate('Finish');?>";
</script>

<div class="container">
	<div class="col-md-10 col-md-offset-1">
		<div class="row">
			<div class="col-md-12 center">
				<div class="page-header-wica">
					<h1><?php echo $lang->translate('New profile'); ?></h1>
				</div>
			</div>	
		</div>
		
		<div class="row">
			
			<div class="col-md-8 col-md-offset-2">
				<?php echo $this->flashMessages();?>
			</div>
			
		</div>
		
		<div class="row-fluid">
			<div class="alert_messages_container hide" id="error_container">						
				<div class="alert alert-danger size_alerts"><div id="alerts" class="bold"></div></div>
			</div>
		</div>
		
		<form action="#" method="post" class="form-horizontal" name="frmCreateProfile" id="frmCreateProfile">
		<div class="row-fluid">		
			<div class="col-md-6 col-md-offset-3">
				<div class="form-group">
					<label class="col-sm-4 control-label form_label"><?php echo '* '.$lang->translate('Profile name').':';?></label>
					<div class="col-sm-8">
                                            <input type="text" class="form-control" name="profile" id="profile" title="<?php echo $lang->translate('Required profile name');?>">
					</div>
				</div>	
			</div>
		</div>
		
		<div class="row">	
			<div class="text-center center-block" id="navigation_info">
				<ul id='steps'></ul>
			</div>
		</div>
		
		<div class="step_containers">	
			<div class="row">
				
				<div class="col-md-4 col-md-offset-4">
					<span>
                                            <h2 class="text-center"><?php echo $lang->translate('Websites'); ?></h2>				
					</span>
				</div>
				
			</div>
			
			<div class="row">
				
				<div class="col-md-4 col-md-offset-4">
				<?php if($this->websites && count($this->websites)>0):?>				
						<?php foreach ($this->websites as $web):?>
							<div class="form-group">
                                                            <label class="col-md-12">
                                                                <p class="col-sm-8 control-label form_label " for="optionsCheckbox"><?php echo $web->name;?></p>
                                                                <div class="col-sm-4 checkbox">
                                                                    <input type="checkbox" name="website[<?php echo $web->id; ?>][website]" nick="<?php echo $web->name;?>" id="website_<?php echo $web->id; ?>">							
                                                                </div>
                                                            </label>
							</div>
						<?php endforeach;?>					
				<?php else:?>
					<h3><?php echo $lang->translate('No Websites');?></h3>				
				<?php endif;?>
					<input type="hidden" name="website_sel" id="website_sel" title="<?php echo $lang->translate('Required website selection'); ?>"/>
				</div>
				
			</div>					
		</div>
		
		<div class="step_containers">		
			<div class="row">	
				
				<div class="col-md-4 col-md-offset-4">
					<span>
                                            <h2 class="text-center"><?php echo $lang->translate('Modules'); ?></h2>				
					</span>
				</div>
				
			</div>	
			
			<?php if (count($this->modules)>0): ?>
			<div class="row">
					
				<div class="col-md-4 col-md-offset-4">			
		  			<?php foreach ($this->modules as $k => $entry):?>
                                        <div class="form-group">
                                            <label class="col-md-12">
                                                <p class="col-sm-8 control-label form_label " for="optionsCheckbox"><?php echo $lang->translate($entry->name);?></p>
                                                <div class="col-sm-4 checkbox">
                                                    <input type="checkbox" name="module[<?php echo $entry->id;?>][module]" id="module_<?php echo $entry->id; ?>"/>
                                                </div>
                                            </label>
                                        </div>
	  				<?php $module_action = new Core_Model_ModuleAction();?>
		  				<?php foreach ($module_action->find ( 'wc_module_action', array('module_id'=>$entry->id) ) as $key => $action): ?>	
		  				<div class="form-group">
							<div class="col-sm-offset-8 col-sm-4 checkbox">
								<label>
									<input type="checkbox" name="module[<?php echo $entry->id; ?>][<?php echo $action->id; ?>][action]" parent="<?php echo $entry->id; ?>" id="module_<?php echo $entry->id.'_'.$action->id; ?>">
									<?php echo $lang->translate($action->title); ?>							
								</label>
							</div>
						</div>		
		  				<?php endforeach ?>		  		  	
		  			<?php endforeach ?>
				</div>
				
			</div>		 
			<?php endif ?>		
			<input type="hidden" name="module_sel" id="module_sel" title="<?php echo $lang->translate('Required module selection'); ?>"/>				
		</div>
		
		<div class="step_containers">
			<div class="row">	
				
				<div class="col-md-4 col-md-offset-4">
					<span>
                                            <h2 class="text-center"><?php echo $lang->translate('Sections'); ?></h2>				
					</span>
				</div>
				
			</div>	
			<div class="row">
				
				<div class="col-md-4" id="messages"><?php echo $lang->translate('Section config not required'); ?></div>
						
			</div>
			<div class="row hide" id="web_container">
				
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<label class="col-sm-5 control-label form_label"><?php echo '* '.$lang->translate('Website Name').':';?></label>			
						<div class="col-sm-7" id="websites">				
						</div>
					</div>
				</div>
						
			</div>
			<div class="row">
				
				<div class="col-md-4 col-md-offset-4" id="section_container"></div>
				
			</div>
			<input type="hidden" name="section_sel" id="section_sel" title="<?php echo $lang->translate('Required section selection'); ?>"/>
		</div>		
		</form>
	</div>
	
	
</div>

