<!-- 
 *	View that contain profile options
 *
 * @category   WicaWeb
 * @package    Core_View
 * @copyright  Copyright (c) WicaWeb - Mushoq 
 * @license    GNP
 * @version    1.0
 * @author	   David Rosales
 -->
 
<?php $lang = Zend_Registry::get('Zend_Translate'); ?>

<script type="text/javascript" charset="utf-8">
	var next_step = "<?php echo $lang->translate('Next step');?>";
	var back_step = "<?php echo $lang->translate('Back step');?>";
	var last_step = "<?php echo $lang->translate('Finish');?>";
</script>

<div class="row-fluid">
	<div class="span2">&nbsp;</div>
	
	<div class="span8">
		<div class="row-fluid">
			<div class="span12 center">
				<div class="page-header-wica">
					<h1><?php echo $lang->translate('New profile'); ?></h1>
				</div>
			</div>	
		</div>
		
		<div class="row-fluid">
			<div class="span2">&nbsp;</div>
			<div class="span8">
				<?php echo $this->flashMessages();?>
			</div>
			<div class="span2">&nbsp;</div>
		</div>
		
		<div class="row-fluid">
			<div class="alert_messages_container hide" id="error_container">						
				<div class="alert alert-error size_alerts"><div id="alerts" class="bold"></div></div>
			</div>
		</div>
		
		<form action="#" method="post" class="form-horizontal" name="frmCreateProfile" id="frmCreateProfile">
		<div class="row-fluid">	
			<div class="span4">&nbsp;</div>	
			<div class="span4">
				<div class="control-group">
					<label class="control-label"><?php echo '* '.$lang->translate('Profile name').':';?></label>
					<div class="controls">
						<input type="text" name="profile" id="profile" title="<?php echo $lang->translate('Required profile name');?>">
					</div>
				</div>	
			</div>
			<div class="span4">&nbsp;</div>
		</div>
		
		<div class="row-fluid">	
			<div class="span12" id="navigation_info">
				<ul id='steps'></ul>
			</div>
		</div>
		
		<div class="step_containers">	
			<div class="row-fluid">
				<div class="span4">&nbsp;</div>	
				<div class="span4">
					<span>
						<h2><?php echo $lang->translate('Websites'); ?></h2>				
					</span>
				</div>
				<div class="span4">&nbsp;</div>
			</div>
			
			<div class="row-fluid">
				<div class="span4">&nbsp;</div>
				<div class="span4">
				<?php if($this->websites && count($this->websites)>0):?>				
						<?php foreach ($this->websites as $web):?>
							<div class="control-group">
								<label class="control-label" for="optionsCheckbox"><?php echo $web->name;?></label>
								<div class="controls">
									<label class="checkbox">
										<input type="checkbox" name="website[<?php echo $web->id; ?>][website]" nick="<?php echo $web->name;?>" id="website_<?php echo $web->id; ?>">							
									</label>
								</div>
							</div>
						<?php endforeach;?>					
				<?php else:?>
					<h3><?php echo $lang->translate('No Websites');?></h3>				
				<?php endif;?>
					<input type="hidden" name="website_sel" id="website_sel" title="<?php echo $lang->translate('Required website selection'); ?>"/>
				</div>
				<div class="span4">&nbsp;</div>
			</div>					
		</div>
		
		<div class="step_containers">		
			<div class="row-fluid">	
				<div class="span4">&nbsp;</div>
				<div class="span4">
					<span>
						<h2><?php echo $lang->translate('Modules'); ?></h2>				
					</span>
				</div>
				<div class="span4">&nbsp;</div>
			</div>	
			
			<?php if (count($this->modules)>0): ?>
			<div class="row-fluid">
				<div class="span4">&nbsp;</div>	
				<div class="span4">			
		  			<?php foreach ($this->modules as $k => $entry):?>	  	
	  	 			<div class="control-group">
						<label class="control-label" for="optionsCheckbox"><b><?php echo $lang->translate($entry->name);?></b></label>
						<div class="controls">
							<label class="checkbox">
								<input type="checkbox" name="module[<?php echo $entry->id;?>][module]" id="module_<?php echo $entry->id; ?>"/>							
							</label>
						</div>
					</div>
	  				<?php $module_action = new Core_Model_ModuleAction();?>
		  				<?php foreach ($module_action->find ( 'wc_module_action', array('module_id'=>$entry->id) ) as $key => $action): ?>	
		  				<div class="control-group">
							<label class="control-label" for="optionsCheckbox"></label>
							<div class="controls">
								<label class="checkbox">
									<input type="checkbox" name="module[<?php echo $entry->id; ?>][<?php echo $action->id; ?>][action]" parent="<?php echo $entry->id; ?>" id="module_<?php echo $entry->id.'_'.$action->id; ?>">
									<?php echo $lang->translate($action->title); ?>							
								</label>
							</div>
						</div>		
		  				<?php endforeach ?>		  		  	
		  			<?php endforeach ?>
				</div>
				<div class="span4">&nbsp;</div>
			</div>		 
			<?php endif ?>		
			<input type="hidden" name="module_sel" id="module_sel" title="<?php echo $lang->translate('Required module selection'); ?>"/>				
		</div>
		
		<div class="step_containers">
			<div class="row-fluid">	
				<div class="span4">&nbsp;</div>
				<div class="span4">
					<span>
						<h2><?php echo $lang->translate('Sections'); ?></h2>				
					</span>
				</div>
				<div class="span4">&nbsp;</div>
			</div>	
			<div class="row-fluid">
				<div class="span4">&nbsp;</div>
				<div class="span4" id="messages"><?php echo $lang->translate('Section config not required'); ?></div>
				<div class="span4">&nbsp;</div>		
			</div>
			<div class="row-fluid hide" id="web_container">
				<div class="span4">&nbsp;</div>
				<div class="span4">
					<div class="control-group">
						<label class="control-label"><?php echo '* '.$lang->translate('Website Name').':';?></label>			
						<div class="controls" id="websites">				
						</div>
					</div>
				</div>
				<div class="span4">&nbsp;</div>		
			</div>
			<div class="row-fluid">
				<div class="span4">&nbsp;</div>
				<div class="span4" id="section_container"></div>
				<div class="span4">&nbsp;</div>
			</div>
			<input type="hidden" name="section_sel" id="section_sel" title="<?php echo $lang->translate('Required section selection'); ?>"/>
		</div>		
		</form>
	</div>
	
	<div class="span2">&nbsp;</div>
</div>

