<?php 
/**
 * Index View. Renders the view of the index action 
 *
 * @category   WicaWeb
 * @package    Core_View_Website_Index
 * @copyright  Copyright (c) WicaWeb - Mushoq
 * @license    GNP
 * @author	   Esteban
 * @version    1.0
 *
 */
//translate library
$lang = Zend_Registry::get('Zend_Translate');
?>

<?php foreach($this->website_links as $action_id => $opt): ?>
<?php if($opt['action']=='new'): ?>
<div class="row-fluid option_bar_container">
	<ul class="nav nav-pills pull-right">
		<li>
			<a href="/core/website_website/new"><?php echo $lang->translate('New Website'); ?></a>
		</li>
	</ul>
</div>
<?php endif; ?>
<?php endforeach; ?>

<div class="line-top alert_messages_container">
	<?php echo $this->flashMessages();?>
</div>

<div class="row-fluid center">
	<div class="span12 page-header-wica">
		<h1> <?php echo $lang->translate('Website List');?> </h1>
	</div>
</div>

<?php if($this->websites && count($this->websites)>0):?>
<div class="row-fluid">
	<table class="table table-bordered table-bordered-wica">
		<tr>
			<th> <?php echo $lang->translate('Image');?> </th>
			<th> <?php echo $lang->translate('Name');?> </th>
			<th> <?php echo $lang->translate('Default Website');?> </th>
			<th> <?php echo $lang->translate('Tools');?> </th>
		</tr>
		<?php foreach ($this->websites as $k=>$web):?>
		<tr class="<?php if(($k+1)%2): echo "odd"; endif;?>">
			<td class="center"><?php if($web->logo != NULL && $web->logo!=''): ?> <img src="/uploads/website/<?php echo $web->logo;?>" alt="<?php echo $web->logo;?>" width="80"> <?php endif;?></td>
			<td><?php echo $web->name;?></td>
			<td id="default_page" class="center">
				<?php if($web->default_page == 'yes'): ?>
					<a href='/core/website_website/defaultpage?id=<?php echo $web->id;?>' title="<?php echo $lang->translate('Default Website'); ?>"><i class="icon-ok"></i></a>
				<?php elseif($web->default_page == 'no'): ?>
					<a href='/core/website_website/defaultpage?id=<?php echo $web->id;?>' title="<?php echo $lang->translate('Change Default Website'); ?>"><i class="icon-remove"></i></a>
				<?php endif;?>
			</td>
			<td>
				<?php foreach($this->website_links as $action_id => $opt): ?>
					<?php if($opt['action']=='edit'): ?>
						<a href='/core/website_website/edit?id=<?php echo $web->id;?>'><i class="icon-pencil" title="<?php echo $lang->translate('Update'); ?>"></i></a>
					<?php endif; ?>
				<?php endforeach; ?>
			</td>
		</tr>	
		<?php endforeach;?>
	</table>
</div>
<?php else:?>
	<div class="row-fluid center line">
		<h3><?php echo $lang->translate('No Websites');?></h3>
	</div>
	<div class="row-fluid center line-top">
				<a class="btn btn-success btn-large" href="/core/website_website/new"><?php echo $lang->translate('New Website'); ?></a>
	</div>
<?php endif;?>
</div>